import { CategoryDefinition } from '../types/base.types';

/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable @typescript-eslint/quotes */

export const AslWordsCategories: Readonly<CategoryDefinition[]> = [
    {
        name: 'Daily Use',
        words: [
            'ASL-Hello',
            'ASL-How Are You',
            'ASL-Whatsup',
            'whats up',
            'gt4nicemeetyou',
            'ASL-Good',
            'ASL-Bad',
            'gt4yes',
            'gt4no',
            'gt4soso',
            'gt4sick',
            'sick',
            'hurt (fingers too far apart)',
            'ASL-Your Welcome',
            'goodbyetxt',
            'ASL-Good Morning',
            'ASL-Good Afternoon',
            'ASL-Good Evening',
            'ASL-Good Night',
            'gt4seeyoulater',
            'gt4please',
            'gt4sorry',
            'gt4forget',
            'gt4sleep',
            'ASL-Bed',
            'gt4jumpchangeworlds',
            'thankyoutxt',
            'gt4iloveyou',
            'ASL-ILY',
            'ASL-Go Away',
            'gt4goingto',
            'gt4follow',
            'ASL-Come',
            'gt4hearing',
            'gt4deaf',
            'gt4deaf2',
            'gt4hoh',
            'ASL-Mute',
            'gt4writeslow',
            'gt4cantread',
            'ASL-Away',
        ],
    },
    {
        name: 'Pointing use Question / Answer',
        words: [
            'ASL-I',
            'ASL-Him',
            'ASL-Her',
            'ASL-My',
            'ASL-Your',
            'ASL-We',
            'ASL-They',
            'ASL-Their',
            'gt4overthere',
            'ASL-Our',
            'ASL-Its',
            'ASL-Inside',
            'ASL-Outside',
            'ASL-Outside (Outdoors)',
            'ASL-Hidden',
            'ASL-Behind',
            'ASL-Above',
            'ASL-Below',
            'ASL-Here',
            'ASL-Beside',
            'gt4back',
            'gt4front',
            'ASL-Who',
            'ASL-Where',
            'ASL-When',
            'ASL-Why',
            'ASL-Which',
            'ASL-What',
            'ASL-What2',
            'ASL-How',
            'ASL-How_0',
            'ASL-How Many',
            'ASL-How Many2',
            'ASL-Can',
            "ASL-Can't",
            'ASL-Want',
            'ASL-Have',
            'ASL-Get',
            'ASL-Will',
            'ASL-Take',
            'gt4need',
            'ASL-Must',
            'ASL-Not',
            'ASL-Or',
            'ASL-And',
            'ASL-For',
        ],
    },
    {
        name: 'Common',
        words: [
            'ASL-GT4tube-Teach',
            'ASL-Learn',
            'ASL-Person',
            'ASL-Student',
            'ASL-Teacher',
            'ASL-GT4tube-Friends',
            'ASL-Sign',
            'ASL-Language',
            'ASL-Understand',
            'ASL-Know',
            "ASL-Don't Know",
            'ASL-Be Right Back (BRB)',
            'ASL-Accept',
            'ASL-Denial',
            'ASL-Name',
            'ASL-New',
            'ASL-Old',
            'ASL-Very',
            'ASL-Jokes',
            'ASL-Funny',
            'ASL-Play',
            'ASL-Favorite',
            'ASL-Draw (Pencil)',
            'ASL-Stop',
            'ASL-Read',
            'ASL-GT4tube-Make',
            'ASL-Write',
            'ASL-Again  Repeat',
            'ASL-Slow',
            'ASL-Fast',
            'ASL-Rude',
            'ASL-Eat',
            'ASL-Drink',
            'ASL-Watch',
            'ASL-Work',
            'ASL-Live',
            'ASL-GT4tube-Live',
            'ASL-Play Game',
            'ASL-Same',
            'ASL-Allright',
            'ASL-People',
            'ASL-Browsing the Internet',
            'ASL-Movie',
        ],
    },
    {
        name: 'People',
        words: [
            'ASL-GT4tube-Family',
            'ASL-Boy',
            'ASL-Girl',
            'ASL-Brother',
            'ASL-Sister',
            'ASL-Brother in Law',
            'ASL-Sister in Law',
            'ASL-Father',
            'ASL-Grandpa',
            'ASL-Mother',
            'ASL-Grandma',
            'ASL-Baby',
            'ASL-Child',
            'ASL-Teen',
            'ASL-Adult',
            'ASL-Aunt',
            'ASL-Uncle',
            'ASL-Stranger',
            'ASL-Acquaintance',
            'ASL-Parents',
            'ASL-Born',
            'ASL-Dead',
            'ASL-Marriage',
            'ASL-Divorce',
            'ASL-Single',
            'ASL-Young',
            'ASL-Old',
            'ASL-Age',
            'ASL-Birthday',
            'ASL-Celebrate',
            'ASL-Enemy',
            'ASL-Interpreter',
            'ASL-No One',
            'ASL-Anyone',
            'ASL-Someone',
            'ASL-Everyone',
        ],
    },
    {
        name: 'Feelings / Reactions',
        words: [
            'ASL-Like',
            'ASL-Hate',
            'ASL-Fine',
            'ASL-Tired',
            'gt4sleep',
            'ASL-Confused',
            'ASL-Smart',
            'ASL-Focus',
            'ASL-Nevermind',
            'ASL-Angry',
            'ASL-Laughing',
            'ASL-LOL',
            'ASL-Curious',
            'ASL-In Love',
            'ASL-Awesome',
            'ASL-Great',
            'ASL-Nice',
            'ASL-Cute',
            'ASL-Feel',
            'ASL-Pity',
            'ASL-Envy',
            'ASL-Hungry',
            // MISSING WORD Alive
            'ASL-Bored',
            'ASL-Cry',
            'ASL-Happy',
            'ASL-Sad',
            'ASL-Suffering',
            'ASL-Surprise',
            'ASL-Careful',
            'ASL-Enjoy',
            'ASL-Disgusted',
            'ASL-Embarassed',
            'ASL-Shy',
            'ASL-Lonely',
            'ASL-Stressed',
            'ASL-Scared',
            'ASL-Excited',
            'ASL-Shame',
            'ASL-Struggle',
            'ASL-Friendly',
            'ASL-Mean',
        ],
    },
    {
        name: 'Value',
        words: [
            'ASL-More',
            'ASL-Less',
            'ASL-Big',
            'ASL-Small',
            'ASL-Full',
            'ASL-Empty',
            'ASL-Half',
            'ASL-Quarter',
            'ASL-Long',
            'ASL-Short',
            'ASL-Many',
            'ASL-Unlimited',
            'ASL-Limited',
            'ASL-GT4tube-All1',
            'ASL-GT4tube-All2',
            'ASL-Nothing',
            'ASL-Ever',
            'ASL-Everything',
            'ASL-Everytime',
            'ASL-GT4tube-Always',
            'ASL-Often',
            'ASL-Sometimes',
            'ASL-GT4tube-Heavy',
            'ASL-Lightweight',
            'ASL-Hard',
            'ASL-Soft',
            'ASL-GT4tube-Strong',
            'ASL-Weak',
            'ASL-First',
            'ASL-Second',
            'ASL-Third',
            'ASL-Next',
            'ASL-Last',
            'ASL-Before',
            'ASL-After',
            'ASL-GT4tube-Busy',
            'ASL-Free',
            'ASL-High',
            'ASL-Low',
            'ASL-Fat',
            'ASL-Thin',
            'ASL-Value',
        ],
    },
    {
        name: 'Time',
        words: [
            'ASL-Time',
            'ASL-Year',
            'ASL-Season',
            'ASL-GT4tube-Month',
            'ASL-Week',
            'ASL-Day',
            'ASL-Weekend',
            'ASL-Hours',
            'ASL-Minutes',
            'ASL-Today',
            'ASL-Tomorrow',
            'ASL-Yesterday',
            'ASL-Morning',
            'ASL-Afternoon',
            'ASL-Evening',
            'ASL-Night',
            'ASL-Sunrise',
            'ASL-Sunset',
            'ASL-All Day',
            'ASL-GT4tube-All Day',
            'ASL-All Night',
            'ASL-GT4tube-All Night',
            'ASL-Sunday',
            'ASL-Monday',
            'ASL-Tuesday',
            'ASL-Wednesday',
            'ASL-Thursday',
            'ASL-Friday',
            'ASL-Saturday',
            'ASL-Autumn',
            'ASL-Winter',
            'ASL-Spring',
            'ASL-Summer',
            'ASL-Now',
            'ASL-Never',
            'ASL-Soon',
            'ASL-Later',
            'ASL-Past',
            'ASL-Future',
            'ASL-Earlier',
            'ASL-Midweek',
            'ASL-Next Week',
        ],
    },
    {
        name: 'VRChat',
        words: [
            'ASL-Gestures',
            'ASL-World',
            'ASL-Record',
            'ASL-Discord',
            'ASL-Streaming',
            'ASL-Headset (VR)',
            'ASL-Desktop',
            'ASL-Computer',
            'ASL-Instance',
            'ASL-Public',
            'ASL-Invite',
            'ASL-Private',
            'ASL-Add Friend',
            'ASL-Menu',
            'ASL-Recharge',
            'ASL-Visit',
            'ASL-Request',
            'ASL-Login',
            'ASL-Logout',
            'ASL-Schedule',
            'ASL-Event',
            'ASL-Online',
            'ASL-Offline',
            'ASL-Cancel',
            'ASL-Portal',
            'ASL-Camera',
            'ASL-Avatar',
            'ASL-Photo',
            'ASL-Join',
            'ASL-Leave',
            'ASL-Climbing',
            'ASL-Falling',
            'ASL-Walk',
            'ASL-Hide',
            'ASL-Block',
            'ASL-Crash',
            'ASL-Lagging',
            'ASL-Restart',
            'ASL-Send',
            'ASL-Receive',
            'ASL-Security',
            'ASL-Donation',
        ],
    },
    {
        name: 'Alphabet / Numbers (Fingerspelling)',
        words: [
            'ASL-Spell',
            // MISSING WORD Spell / Fingerspell (v2) - OCULUS
            'ASL-A',
            'ASL-GT4tube-B-Index',
            'ASL-GT4tube-B-Gen',
            'ASL-C',
            'ASL-D',
            'ASL-E',
            'ASL-F',
            // MISSING WORD F (v2) - OCULUS
            'ASL-G',
            'ASL-H',
            'ASL-I_0',
            // MISSING WORD I (v2) - OCULUS
            'ASL-J',
            // MISSING WORD J (v2) - OCULUS
            'ASL-K',
            // MISSING WORD K (v2)
            'ASL-L',
            'ASL-M',
            // MISSING WORD M (v2)
            'ASL-N',
            // MISSING WORD N (v2)
            'ASL-O',
            'ASL-P',
            'ASL-Q',
            'ASL-R',
            'ASL-S',
            'ASL-T',
            'ASL-U',
            // MISSING WORD U (v2) - OCULUS
            'ASL-V',
            // MISSING WORD V (v2) - OCULUS
            'ASL-W',
            'ASL-GT4tube-W-Gen',
            'ASL-X',
            // MISSING WORD X (v2)
            'ASL-Y',
            // MISSING WORD Y (v2) - OCULUS
            'ASL-Z',
            'ASL-Comma',
            'ASL-Space',
            'ASL-@',
            'ASL-Number',
            'ASL-0',
            'ASL-1',
            'ASL-2',
            'ASL-3',
            'ASL-4',
            'ASL-5',
            'ASL-6',
            'ASL-7',
            'ASL-8',
            'ASL-9',
            'ASL-10',
            'ASL-100',
            'ASL-1000',
            'ASL-1000000',
        ],
    },
    {
        name: 'Verbs & Actions (p1)',
        words: [
            'ASL-Overlook',
            'ASL-Punish',
            'ASL-Edit',
            'ASL-Erase',
            'ASL-Write',
            'ASL-Proposal',
            // MISSING WORD Add - RED
            'ASL-Increase',
            'ASL-Remove',
            'ASL-Agree',
            'ASL-Disagree',
            'ASL-Admit',
            'ASL-Allow',
            'ASL-Attack',
            'ASL-Fight',
            'ASL-Defend',
            'ASL-Defeat (Overcome)',
            'ASL-Win',
            'ASL-Lose',
            'ASL-DrawTie (Game)',
            'ASL-Give up',
            'ASL-Skip',
            'ASL-Ask',
            'ASL-Attach',
            'ASL-Assistant',
            'ASL-Assist  Help',
            'ASL-Bait',
            'ASL-Battle',
            'ASL-Beat (Overcome)',
            'ASL-Become',
            'ASL-Beg',
            'ASL-Begin',
            'ASL-Behave',
            'ASL-Believe',
            'ASL-Blame',
            'ASL-Blow',
            'ASL-Blush',
            'ASL-Harass',
        ],
    },
    {
        name: 'Verbs & Actions (p2: Ben-Cor)',
        words: [
            'ASL-Bend',
            'ASL-Bow',
            'ASL-Break',
            'ASL-Breathe',
            'ASL-Bring',
            'ASL-Construct',
            'ASL-Bully',
            'ASL-Burn',
            'ASL-Buy',
            'ASL-Call',
            'ASL-Cancel',
            'ASL-Care',
            'ASL-Carry',
            'ASL-Catch',
            'ASL-Cause',
            'ASL-Challenge',
            'ASL-Chance',
            'ASL-Cheat',
            'ASL-Check',
            'ASL-Choose',
            'ASL-Claim',
            'ASL-Clean',
            'ASL-Clear',
            'ASL-Close',
            'ASL-Comfort',
            'ASL-Command',
            'ASL-Communicate',
            'ASL-Compare',
            'ASL-Complain',
            'ASL-Compliment',
            'ASL-Concentrate',
            'ASL-Construct',
            'ASL-Control',
            'ASL-Cook',
            'ASL-Copy',
            'ASL-Correct',
        ],
    },
    {
        name: 'Verbs & Actions (p3: Cou-Esc)',
        words: [
            'ASL-Cough',
            'ASL-Count',
            'ASL-Create',
            'ASL-Cuddle',
            'ASL-Cut',
            'ASL-Dab',
            'ASL-Dance',
            'ASL-Dare',
            'ASL-Date',
            'ASL-Deal',
            'ASL-Deliver',
            'ASL-Depend',
            'ASL-Describe',
            'ASL-Dirty',
            'ASL-Disappear',
            'ASL-Disappoint',
            'ASL-Not Accept',
            'ASL-Discuss',
            'ASL-Disguise',
            'ASL-Disgusted',
            'ASL-Dismiss',
            'ASL-Bother',
            'ASL-Doubt',
            'ASL-Dream',
            'ASL-Dress',
            'ASL-Drunk',
            'ASL-Drop',
            'ASL-Drown',
            'ASL-Dry',
            'ASL-Dump',
            'ASL-Dust',
            'ASL-Earn',
            'ASL-Effect',
            'ASL-End',
            'ASL-Escape',
            'ASL-Escort',
        ],
    },
    {
        name: 'Verbs & Actions (p4: Exc-Ins)',
        words: [
            'ASL-Excuse',
            'ASL-Expose',
            'ASL-Exist',
            'ASL-Fail',
            'ASL-Faint',
            'ASL-Fake',
            'ASL-Fart',
            'ASL-Fear',
            'ASL-Fill',
            'ASL-Find',
            'ASL-Finish',
            'ASL-Fix',
            'ASL-Flip',
            'ASL-Flirt',
            'ASL-Fly',
            'ASL-Forbid',
            'ASL-Forgive',
            'ASL-Gain',
            'ASL-Give',
            'ASL-Glow',
            'ASL-Grab',
            'ASL-Grow',
            'ASL-Guard',
            'ASL-Guess',
            'ASL-Guide',
            'ASL-Harass',
            'ASL-Harm',
            'ASL-Hit',
            'ASL-Hold',
            'ASL-Hop',
            'ASL-Hope',
            'ASL-Hunt',
            'ASL-Ignore',
            'ASL-Imagine',
            'ASL-Imitate',
            'ASL-Insult',
        ],
    },
    {
        name: 'Verbs & Actions (p5: Int-Pas)',
        words: [
            'ASL-Interact',
            'ASL-Interfere',
            'ASL-Judge',
            'ASL-Jump',
            'ASL-Justify',
            'ASL-Just Kidding',
            'ASL-Keep',
            'ASL-Kick',
            'ASL-Kill',
            'ASL-Knock',
            'ASL-Lead',
            'ASL-Lick',
            'ASL-Lock',
            'ASL-Manipulate',
            'ASL-Melt',
            'ASL-Mess',
            'ASL-Miss',
            'ASL-Mistake',
            'ASL-Mount',
            'ASL-Move',
            'ASL-Nod',
            'ASL-Note',
            'ASL-Notice',
            'ASL-Obey',
            'ASL-Obsess',
            'ASL-Obtain',
            'ASL-Occupy',
            'ASL-Offend',
            'ASL-Offer',
            'ASL-Okay',
            'ASL-Open',
            'ASL-Order',
            'ASL-Owe',
            'ASL-Own',
            'ASL-Pass',
        ],
    },
    {
        name: 'Verbs & Actions (p6: Pat-Sav)',
        words: [
            'ASL-Pat',
            'ASL-Party',
            'ASL-Pet',
            'ASL-Pick',
            'ASL-Plug',
            'ASL-Point',
            'ASL-Poke',
            'ASL-Pray',
            'ASL-Prepare',
            'ASL-Present',
            'ASL-Pretend',
            'ASL-Protect',
            'ASL-Prove',
            'ASL-Publish',
            'ASL-Puke',
            'ASL-Puke (Variant 2)',
            'ASL-Pull',
            'ASL-Punch',
            'ASL-Put',
            'ASL-Push',
            'ASL-Question',
            'ASL-Questions Plural form',
            'ASL-Quit',
            'ASL-Quote',
            'ASL-Race',
            'ASL-React',
            'ASL-Recommended',
            'ASL-Refuse',
            'ASL-Regret',
            'ASL-Remember',
            'ASL-Replace',
            'ASL-Report',
            'ASL-Reset',
            'ASL-Ride',
            'ASL-Rub',
            'ASL-Rule',
            'ASL-Run',
            'ASL-Save',
        ],
    },
    {
        name: 'Verbs & Actions (p7: Say-Try)',
        words: [
            'ASL-Say',
            'ASL-Search',
            'ASL-See',
            'ASL-Share',
            'ASL-Shock',
            'ASL-Shop',
            'ASL-Show',
            'ASL-Shut up',
            'ASL-Shut Down',
            'ASL-Sing',
            'ASL-Sit',
            'ASL-Smell',
            'ASL-Smile',
            'ASL-Smoke',
            'ASL-Speak',
            'ASL-Spell',
            'ASL-Spit',
            'ASL-Stand',
            'ASL-Start',
            'ASL-Stay',
            'ASL-Steal',
            'ASL-Stop',
            'ASL-Study',
            'ASL-Suffering',
            'ASL-Switch',
            'ASL-Take',
            'ASL-Communicate',
            'ASL-Tell',
            'ASL-Test',
            'ASL-Text',
            'ASL-Think',
            'ASL-Throw',
            'ASL-Tie',
            'ASL-Truth',
            'ASL-Try',
        ],
    },
    {
        name: 'Verbs & Actions (p8)',
        words: [
            'ASL-Type',
            'ASL-Turn',
            'ASL-Upset',
            'ASL-Use',
            'ASL-View',
            'ASL-Vomit',
            'ASL-Wait',
            'ASL-Wakeup',
            'ASL-War',
            'ASL-Warn',
            'ASL-Waste',
            'ASL-Wash',
            'ASL-Watch',
            'ASL-Wear',
            'ASL-Wobble',
            'ASL-Wonder',
            'ASL-Worry',
            'ASL-Work',
            'ASL-Hug',
            'ASL-Touch',
            'ASL-Kiss',
            'ASL-Trust',
            'ASL-True',
            'ASL-Lie',
            'ASL-Serve',
            'ASL-Calculate',
            'ASL-Shower',
            'ASL-Bathe',
            'ASL-Socialize',
            'ASL-Assist  Help',
            'ASL-Support',
            'ASL-Take Care',
            'ASL-Drive',
            'ASL-Travel',
            'ASL-Trip',
            'ASL-Fiction',
        ],
    },
    {
        name: 'Food',
        words: [
            'ASL-Corn',
            'ASL-Vegetable',
            'ASL-Cookie',
            'ASL-Cake',
            'ASL-Yogurt',
            'ASL-Lemon',
            'ASL-Nuts',
            'ASL-Grapes',
            'ASL-Peas',
            'ASL-Icecream',
            'ASL-Pear',
            'ASL-Butter',
            'ASL-Banana',
            'ASL-Pumpkin',
            'ASL-Fruit',
            'ASL-Apple',
            'ASL-Tomato',
            'ASL-Orange_0',
            'ASL-Bread',
            'ASL-Cheese',
            'ASL-Water',
            'ASL-Hamburger',
            'ASL-Hot Dog',
            'ASL-Sandwich',
            'ASL-Taco',
            'ASL-Noodles',
            'ASL-Eggs',
            'ASL-Salt',
            'ASL-Meat',
            'ASL-Carrot',
            'ASL-Cabbage',
            'ASL-Spaghetti',
            'ASL-Pizza',
            'ASL-Sushi',
            'ASL-Potato',
            'ASL-Juice',
            'ASL-Cola',
            'ASL-Beer',
            'ASL-Wine',
            'ASL-Champagne',
            'ASL-Milk',
            'ASL-Sugar',
        ],
    },
    {
        name: 'Animals / Machines',
        words: [
            'ASL-Dog',
            'ASL-Cat',
            'ASL-Fox',
            'ASL-Cow',
            'ASL-Sheep',
            'ASL-Duck',
            'ASL-Turkey (Bird)',
            'ASL-Fly (Insect)',
            'ASL-Chicken',
            'ASL-Owl',
            'ASL-Bird',
            'ASL-Mouse',
            'ASL-Bear',
            'ASL-Lion',
            'ASL-Cricket',
            'ASL-Dragon',
            'ASL-Rabbit',
            'ASL-Turtle',
            'ASL-Pig',
            'ASL-Squirrel',
            'ASL-Raccoon',
            'ASL-Fish',
            'ASL-Rocket',
            'ASL-Generator',
            'ASL-Car',
            'ASL-Truck',
            'ASL-Bike',
            'ASL-Motorcycle',
            'ASL-Train',
            'ASL-Robot',
            'ASL-Spaceship',
            'ASL-Aircraft',
            'ASL-Helicopter',
            'ASL-Bus',
            'ASL-Ship',
            'ASL-Bulldozer',
            'ASL-Crane',
            'ASL-Machine',
            'ASL-Drilling Machine',
            'ASL-Elevator',
            'ASL-Cyborg',
            'ASL-Tank',
            'ASL-Submarine',
        ],
    },
    {
        name: 'Places',
        words: [
            'ASL-Bathroom',
            'ASL-Room',
            'ASL-City',
            'ASL-House',
            'ASL-Skyscraper',
            'ASL-Apartment',
            'ASL-Tower',
            'ASL-Village',
            'ASL-Sewer',
            'ASL-Cellar',
            'ASL-Storage',
            'ASL-Pool',
            'ASL-Sea',
            'ASL-Island',
            'ASL-Sun',
            'ASL-Moon',
            'ASL-Sky',
            'ASL-Outer Space',
            'ASL-Milky Way',
            'ASL-Heaven',
            'ASL-Hell',
            'ASL-Graveyard',
            'ASL-Garden',
            'ASL-Beach',
            'ASL-Coast',
            'ASL-Sea',
            'ASL-Garbage Dump',
            'ASL-Castle',
            'ASL-Cathedral',
            'ASL-Church',
            'ASL-Store',
            'ASL-Butchery',
            'ASL-Prison',
            'ASL-Police Station',
            'ASL-Hospital',
            'ASL-Firestation',
            'ASL-Hotel',
            'ASL-Airport',
            'ASL-Harbor',
            'ASL-Road',
            'ASL-Crossing',
            'ASL-Railway',
        ],
    },
    {
        name: 'Stuff / Weather',
        words: [
            'ASL-Wood',
            'ASL-Metal',
            'ASL-Glass',
            'ASL-Liquid',
            'ASL-Power',
            'ASL-Feather',
            'ASL-Box',
            'ASL-Container',
            'ASL-Paper',
            'ASL-Pencil',
            'ASL-Eraser',
            'ASL-Book',
            'ASL-Ruler',
            'ASL-Hammer',
            'ASL-Saw',
            'ASL-Sander',
            'ASL-Scissors',
            'ASL-Pincer',
            'ASL-Stick',
            'ASL-Rake',
            'ASL-Shovel',
            'ASL-Axe',
            'ASL-Hook',
            'ASL-Chain',
            'ASL-Storm',
            'ASL-Hurricane',
            'ASL-Earthquake',
            'ASL-Dark',
            'ASL-Light',
            'ASL-Clouds',
            'ASL-Fire',
            'ASL-Ice',
            'ASL-Rain',
            'ASL-Flood',
            'ASL-Smoke',
            'ASL-Fog',
            'ASL-Snow',
            'ASL-Freeze',
            'ASL-Hot',
            'ASL-Humidity',
            'ASL-Lightning',
        ],
    },
    {
        name: 'Clothes / Equipment',
        words: [
            'ASL-Dress',
            'ASL-Pants',
            'ASL-Jeans',
            'ASL-Shorts',
            'ASL-Swimming Trunks',
            'ASL-Bikini',
            'ASL-Miniskirt',
            'ASL-Underwear',
            'ASL-Bra',
            'ASL-Diapers',
            'ASL-Shirt',
            'ASL-Sweater',
            'ASL-Hat',
            'ASL-High Heels',
            'ASL-Scarf',
            'ASL-Raincoat',
            'ASL-Jacket',
            'ASL-Umbrella',
            'ASL-Gloves',
            'ASL-Uniform',
            'ASL-Overalls',
            'ASL-Mask',
            'ASL-Cap',
            'ASL-Glasses',
            'ASL-Goggles',
            'ASL-Helmet',
            'ASL-Socks',
            'ASL-Shoes',
            'ASL-Boots',
            'ASL-Sandals',
            'ASL-Backpack',
            'ASL-Bag',
            'ASL-Suitcase',
            'ASL-Belt',
            'ASL-Sportswear',
            'ASL-Jumpsuit',
            'ASL-Jewelry',
            'ASL-Ring',
            'ASL-Bracelet',
            'ASL-Badge',
            'ASL-Necklace',
            'ASL-Earring',
        ],
    },
    {
        name: 'Fantasy / Characters',
        words: [
            'ASL-Sword',
            'ASL-Shield',
            'ASL-Cannon',
            'ASL-Stick',
            'ASL-Magic',
            'ASL-Money',
            'ASL-Ghost',
            'ASL-Zombie',
            'ASL-Soldier',
            'ASL-Police',
            'ASL-Nurse',
            'ASL-Fireman',
            'ASL-Wizard',
            'ASL-Sorcerer',
            'ASL-Hunter',
            'ASL-Male',
            'ASL-Female',
            'ASL-Human',
            'ASL-Dwarf',
            'ASL-Elf',
            'ASL-Orc',
            'ASL-Tauren',
            'ASL-Monster',
            'ASL-Gnome',
            'ASL-Troll',
            'ASL-Health',
            'ASL-Mana',
            'ASL-Energy',
            'ASL-Power',
            'ASL-Armor',
            'ASL-Resistance',
            'ASL-Resurrect',
            'ASL-Rage',
            'ASL-Casting',
            'ASL-Shooting',
            'ASL-Damage',
            'ASL-Healing',
            'ASL-Melee',
            'ASL-Ammo',
            'ASL-Ranged',
        ],
    },
    {
        name: 'Holidays / Special Days',
        words: [
            'ASL-Holiday',
            'ASL-Pentecost',
            'ASL-Christmas',
            'ASL-Easter',
            "ASL-New Year's Day",
            "ASL-New Year's Eve",
            'ASL-Ascension Day',
            'ASL-Labor Day',
            'ASL-Columbus Day',
            'ASL-Veterans Day',
            'ASL-Thanksgiving Day',
            'ASL-Memorial Day',
            'ASL-Martin Luther King Jr Day',
            "ASL-Presidents' Day",
            "ASL-St Andrew's Day",
            "ASL-St David's Day",
            "ASL-Father's Day",
            "ASL-Mother's Day",
            'ASL-Independence Day',
            'ASL-National Day',
            "ASL-Valentine's Day",
            'ASL-White Day',
            'ASL-Black Friday',
            'ASL-Cyber Monday',
            'ASL-Golden Week',
            "ASL-Doll's Festival (Hina Matsuri)",
            'ASL-Coming of Age Day',
            'ASL-Culture Day',
            "ASL-Children's Day",
            'ASL-Seollal Holiday',
            'ASL-Chinese New Year',
            'ASL-Groundhog Day',
            'ASL-Carnival',
            'ASL-Halloween',
            "ASL-St Patrick's Day",
            "ASL-Parent's Day",
        ],
    },
    {
        name: 'Home stuff',
        words: [
            'ASL-Chair',
            'ASL-Bench',
            'ASL-Couch',
            'ASL-Table',
            'ASL-Computer',
            'ASL-Closet',
            'ASL-Toilet',
            'ASL-Door',
            'ASL-Window',
            'ASL-Roof',
            'ASL-Floorcarpet',
            'ASL-Safe',
            'ASL-Stairs',
            'ASL-Television',
            'ASL-Radio',
            'ASL-Microphone',
            'ASL-Guitar1',
            'ASL-Guitar2',
            'ASL-Drum Kit',
            'ASL-Headphone',
            'ASL-Headphones (Variant 2)',
            'ASL-Washing Machine',
            'ASL-Refrigerator',
            'ASL-Broom',
            'ASL-Sweeper',
            'ASL-Dishwasher',
            // MISSING WORD Cooking Pan - RED
            'ASL-Oven',
            'ASL-Fork',
            'ASL-Knife',
            'ASL-Spoon',
            'ASL-Bowl',
            'ASL-Plate',
            'ASL-Wall Outlet',
            'ASL-Bath',
            'ASL-Shower',
            'ASL-Fireplace',
            'ASL-Fireplace2',
            'ASL-Air Conditioner',
        ],
    },
    {
        name: 'Nature / Environment',
        words: [
            'ASL-Nature',
            'ASL-Environment',
            'ASL-Flower',
            'ASL-Grass',
            'ASL-Tree',
            'ASL-Sand',
            'ASL-Soil',
            'ASL-Waterfall',
            'ASL-Hills',
            'ASL-Cave',
            'ASL-Pine',
            'ASL-Oak',
            'ASL-Sunflower',
            'ASL-Bush',
            'ASL-Dam',
            'ASL-Bridge',
            'ASL-Ocean',
            'ASL-Lake',
            'ASL-Pond',
            'ASL-River',
            'ASL-Rainbow',
            'ASL-Forest',
            'ASL-Wilderness',
            'ASL-Geology',
            'ASL-Ecology',
            'ASL-Evolution',
            'ASL-Matter',
            'ASL-Lava',
            'ASL-Structure',
            'ASL-Rocks',
            'ASL-Atmosphere',
            'ASL-Climate',
            'ASL-Oxygen',
            'ASL-Water Vapor',
            'ASL-Ecosystem',
            'ASL-Life',
            'ASL-Biology',
            'ASL-Organisms',
            'ASL-Reproduction',
            'ASL-Growth',
            'ASL-Microbes',
        ],
    },
    {
        name: 'Talk / Asking exercises (SEE)',
        words: [
            'ASL-Can you teach me',
            "ASL-Sorry, I don't understand",
            'ASL-I want to learn sign language',
            'ASL-My name is',
            'ASL-Please wait for it',
            'ASL-My friend wants to join',
            'ASL-I want to play with you',
            "ASL-I'm slow at learning",
            'ASL-Can you repeat it',
            'ASL-Shall we begin',
            "ASL-I'm busy streaming",
            "ASL-Please don't disturb me",
            'ASL-Can you stop that',
            'ASL-Please follow me',
            'ASL-I want to change the world',
            'ASL-Can you write it down',
            "ASL-Please don't speak",
            "ASL-I can't hear you",
            'ASL-What are the rules',
            'ASL-Can you explain that to me',
            'ASL-Please lead me',
            'ASL-I have good idea',
            "ASL-I'm not feeling good",
            'ASL-How old are you',
            'ASL-Where are you from',
            'ASL-You want to become friends',
            "ASL-I'm going to sleep",
            'ASL-I have to work soon',
            'ASL-What is your Discord',
            'ASL-Can we talk on Discord',
            'ASL-Check your Discord',
            "ASL-I'm lost here",
            "ASL-I'm going to my friend's",
            "ASL-I don't have much time",
        ],
    },
    {
        name: 'Countries',
        words: [
            'ASL-World',
            'ASL-Europe',
            'ASL-Asia',
            'ASL-Country',
            'ASL-North America',
            'ASL-Central America',
            'ASL-South America',
            'ASL-AmericaUSA',
            'ASL-Canada',
            'ASL-Mexico',
            'ASL-Spain',
            'ASL-France',
            'ASL-England',
            'ASL-Netherlands',
            'ASL-Germany',
            'ASL-Scandinavia',
            'ASL-Middle East',
            'ASL-Australia',
            'ASL-Japan',
            'ASL-China',
            'ASL-South Korea',
            'ASL-Russia',
            'ASL-New Zealand',
            'ASL-Brazil',
            'ASL-Poland',
            'ASL-Turkey',
            'ASL-Israel',
            'ASL-Egypt',
            'ASL-Africa',
            'ASL-South Africa',
            'ASL-Norway',
            'ASL-Sweden',
            'ASL-Finland',
            'ASL-Austria',
            'ASL-Italy',
            'ASL-Portugal',
            'ASL-Romania',
            'ASL-Saudi Arabia',
            'ASL-Ireland',
            'ASL-Scotland',
        ],
    },
    {
        name: 'Colors',
        words: [
            'ASL-Color',
            'ASL-White',
            'ASL-Black',
            'ASL-Red',
            'ASL-Blue',
            'ASL-Green',
            'ASL-Brown',
            'ASL-Pink',
            'ASL-Purple',
            'ASL-Yellow',
            'ASL-Orange',
            'ASL-Gold',
            'ASL-Silver',
            'ASL-Transparent',
            'ASL-Gray',
            'ASL-Light',
            'ASL-Dark',
            'ASL-Light Blue',
            'ASL-Dark Blue',
            'ASL-Tan',
            'ASL-Blond',
        ],
    },
    {
        name: 'Materials',
        words: [
            'ASL-Gas',
            'ASL-Oil',
            'ASL-Glow',
            'ASL-Wood',
            'ASL-Metal',
            'ASL-Glass',
            'ASL-Paper',
            'ASL-Plastic',
            'ASL-Rubber',
            'ASL-Foil',
            'ASL-Clay',
            'ASL-Water',
            'ASL-Gel',
            'ASL-Sticker',
            'ASL-Rope',
            'ASL-Wire',
            'ASL-Air',
        ],
    },
    {
        name: 'Medical',
        words: [
            'ASL-Doctor',
            'ASL-Nurse',
            'ASL-Hospital',
            'gt4sick',
            'hurt (fingers too far apart)',
            'ASL-Fever',
            'ASL-Diarrhea',
            'ASL-Vomit',
            'ASL-Healthy',
            'ASL-Better',
            'ASL-Recover',
            'ASL-Pill',
            'ASL-Dead (Variant 2)',
            'ASL-Brain',
            'ASL-Receipt',
            'ASL-Headache',
            'ASL-Stomachache',
            'ASL-Pain',
            'ASL-Bone Fracture',
            'ASL-Wheelchair',
            'ASL-Dentist',
            'ASL-Band Aid',
            'ASL-Bandage',
            'ASL-Wound',
            'ASL-Blood',
            'ASL-Crutch',
            'ASL-Eye',
            'ASL-Ears',
            'ASL-Nose',
            'ASL-Arm',
            'ASL-Legs',
            'ASL-Breast',
            'ASL-Belly',
            'ASL-Mouth',
            'ASL-Finger',
            'ASL-Elbow',
            'ASL-Knee',
            'ASL-Ankle',
            'ASL-Spine',
            'ASL-Skeleton',
            'ASL-Skin',
        ],
    },
] as const;
