import { AslWord } from './asl-words';
import { WordDefinition } from '../types/base.types';

/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable @typescript-eslint/quotes */

export const AslWordsDefinitions: Record<AslWord, WordDefinition> = {
    'ASL-0': { index: true },
    'ASL-1': { index: true },
    'ASL-10': { index: true },
    'ASL-100': { index: true },
    'ASL-1000': { index: true },
    'ASL-1000000': { index: true },
    'ASL-2': { index: true },
    'ASL-3': { index: true },
    'ASL-4': { index: true },
    'ASL-5': { index: true },
    'ASL-6': { index: true },
    'ASL-7': { index: true },
    'ASL-8': { index: true },
    'ASL-9': { index: true },
    'ASL-@': {},
    'ASL-A': {},
    'ASL-Above': {},
    'ASL-Accept': {},
    'ASL-Acquaintance': {},
    'ASL-Add Friend': { red: true },
    'ASL-Admit': {},
    'ASL-Adult': {},
    'ASL-Africa': { red: true },
    'ASL-After': { red: true },
    'ASL-Afternoon': {},
    'ASL-Again  Repeat': { name: 'Again / Repeat' },
    'ASL-Age': {},
    'ASL-Agree': { red: true },
    'ASL-Air Conditioner': {},
    'ASL-Air': {},
    'ASL-Aircraft': {},
    'ASL-Airport': {},
    'ASL-All Day': {},
    'ASL-All Night': {},
    'ASL-Allow': {},
    'ASL-Allright': {},
    'ASL-Aluminium': {},
    'ASL-AmericaUSA': { name: 'America / Usa' },
    'ASL-Ammo': { red: true },
    'ASL-And': {},
    'ASL-Angry': {},
    'ASL-Ankle': { red: true },
    'ASL-Anyone': { red: true },
    'ASL-Apartment': {},
    'ASL-Apple': {},
    'ASL-Arm': {},
    'ASL-Armor': {},
    'ASL-Ascension Day': { red: true },
    'ASL-Asia': {},
    'ASL-Ask': { index: true },
    'ASL-Assist  Help': { name: 'Assist / Help' },
    'ASL-Assistant': { red: true },
    'ASL-At': {},
    'ASL-Atmosphere': { red: true },
    'ASL-Attach': { index: true },
    'ASL-Attack': {},
    'ASL-Aunt': {},
    'ASL-Australia': { red: true },
    'ASL-Austria': { red: true },
    'ASL-Autumn': {},
    'ASL-Avatar': { red: true },
    'ASL-Away': {},
    'ASL-Awesome': { red: true },
    'ASL-Axe': {},
    'ASL-Baby': {},
    'ASL-Backpack': { red: true },
    'ASL-Bad': {},
    'ASL-Badge': { index: true },
    'ASL-Bag': {},
    'ASL-Bait': { red: true },
    'ASL-Banana': {},
    'ASL-Band Aid': {},
    'ASL-Bandage': {},
    'ASL-Bath': {},
    'ASL-Bathe': {},
    'ASL-Bathroom': {},
    'ASL-Battle': {},
    'ASL-Be Right Back (BRB)': {},
    'ASL-Beach': { red: true },
    'ASL-Bear': {},
    'ASL-Beat (Overcome)': {},
    'ASL-Become': {},
    'ASL-Bed': {},
    'ASL-Beer': { red: true },
    'ASL-Before': {},
    'ASL-Beg': { index: true },
    'ASL-Begin': { index: true, name: 'Begin / Start' },
    'ASL-Behave': {},
    'ASL-Behind': {},
    'ASL-Believe': {},
    'ASL-Belly': {},
    'ASL-Below': {},
    'ASL-Belt': {},
    'ASL-Bench': {},
    'ASL-Bend': {},
    'ASL-Beside': {},
    'ASL-Better': {},
    'ASL-Big': {},
    'ASL-Bike': {},
    'ASL-Bikini': {},
    'ASL-Biology': { red: true },
    'ASL-Bird': {},
    'ASL-Birthday': { index: true },
    'ASL-Black Friday': {},
    'ASL-Black': {},
    'ASL-Blame': {},
    'ASL-Block': { red: true },
    'ASL-Blond': {},
    'ASL-Blood': {},
    'ASL-Blow': {},
    'ASL-Blue': { red: true },
    'ASL-Blush': {},
    'ASL-Bone Fracture': {},
    'ASL-Book': {},
    'ASL-Boots': { red: true },
    'ASL-Bored': {},
    'ASL-Born': { red: true },
    'ASL-Bother': {},
    'ASL-Bother_0': {},
    'ASL-Bow': { index: true },
    'ASL-Bowl': {},
    'ASL-Box': {},
    'ASL-Boy': {},
    'ASL-Bra': {},
    'ASL-Bracelet': { index: true },
    'ASL-Brain': {},
    'ASL-Brazil': { red: true },
    'ASL-Bread': {},
    'ASL-Break': {},
    'ASL-Breast': {},
    'ASL-Breathe': {},
    'ASL-Bridge': { red: true },
    'ASL-Bring': { red: true },
    'ASL-Broom': {},
    'ASL-Brother in Law': {},
    'ASL-Brother': {},
    'ASL-Brown': { red: true },
    'ASL-Browsing the Internet': { index: true },
    'ASL-Bulldozer': {},
    'ASL-Bully': { red: true, index: true },
    'ASL-Burn': { index: true },
    'ASL-Bus': { red: true },
    'ASL-Bush': {},
    'ASL-Butchery': { red: true },
    'ASL-Butter': {},
    'ASL-Buy': {},
    'ASL-C': {},
    'ASL-Cabbage': {},
    'ASL-Cake': { red: true },
    'ASL-Calculate': { index: true },
    'ASL-Call': { index: true },
    'ASL-Camera': { red: true },
    'ASL-Can we talk on Discord': {},
    'ASL-Can you explain that to me': {},
    'ASL-Can you help me': {},
    'ASL-Can you repeat it': { name: 'Can you sign again please?' },
    'ASL-Can you stop that': {},
    'ASL-Can you teach me': { red: true },
    'ASL-Can you write it down': {},
    "ASL-Can't": {},
    'ASL-Can': {},
    'ASL-Canada': {},
    'ASL-Cancel': { red: true },
    'ASL-Cannon': {},
    'ASL-Cap': { index: true },
    'ASL-Car': {},
    'ASL-Care': {},
    'ASL-Careful': { index: true },
    'ASL-Carnival': { red: true },
    'ASL-Carrot': {},
    'ASL-Carry': {},
    'ASL-Casting': { red: true },
    'ASL-Castle': {},
    'ASL-Cat': {},
    'ASL-Catch': {},
    'ASL-Cathedral': {},
    'ASL-Cause': {},
    'ASL-Cave': {},
    'ASL-Celebrate': { index: true },
    'ASL-Cellar': {},
    'ASL-Central America': {},
    'ASL-Chain': {},
    'ASL-Chair': {},
    'ASL-Challenge': {},
    'ASL-Champagne': {},
    'ASL-Chance': {},
    'ASL-Cheat': { red: true },
    'ASL-Check your Discord': {},
    'ASL-Check': {},
    'ASL-Cheese': {},
    'ASL-Chicken': {},
    'ASL-Child': { red: true },
    "ASL-Children's Day": {},
    'ASL-China': {},
    'ASL-Chinese New Year': { red: true },
    'ASL-Choose': {},
    'ASL-Christmas': {},
    'ASL-Church': {},
    'ASL-City': { red: true },
    'ASL-Claim': {},
    'ASL-Clay': { red: true },
    'ASL-Clean': {},
    'ASL-Clear': { red: true },
    'ASL-Climate': {},
    'ASL-Climbing': { red: true },
    'ASL-Close': { red: true },
    'ASL-Closet': {},
    'ASL-Clouds': {},
    'ASL-Coast': { red: true },
    'ASL-Cola': {},
    'ASL-Color': {},
    'ASL-Columbus Day': {},
    'ASL-Come': {},
    'ASL-Comfort': {},
    'ASL-Coming of Age Day': {},
    'ASL-Comma': { index: true },
    'ASL-Command': {},
    'ASL-Communicate': { red: true },
    'ASL-Compare': {},
    'ASL-Complain': {},
    'ASL-Compliment': {},
    'ASL-Computer': { red: true },
    'ASL-Concentrate': {},
    'ASL-Confused': {},
    'ASL-Construct': { name: 'Build / Construct' },
    'ASL-Container': { red: true },
    'ASL-Control': {},
    'ASL-Cook': {},
    'ASL-Cookie': {},
    'ASL-Copy': {},
    'ASL-Corn': {},
    'ASL-Correct': {},
    'ASL-Cotton': {},
    'ASL-Couch': {},
    'ASL-Cough': {},
    'ASL-Count': { index: true },
    'ASL-Country': {},
    'ASL-Cow': {},
    'ASL-Crane': {},
    'ASL-Crash': { red: true },
    'ASL-Create': { name: 'Create / Make' },
    'ASL-Cricket': {},
    'ASL-Crossing': {},
    'ASL-Crutch': {},
    'ASL-Cry': {},
    'ASL-Cuddle': {},
    'ASL-Culture Day': { red: true },
    'ASL-Curious': { index: true },
    'ASL-Cut': {},
    'ASL-Cute': {},
    'ASL-Cyber Monday': {},
    'ASL-Cyborg': { red: true },
    'ASL-D': {},
    'ASL-Dab': {},
    'ASL-Dam': {},
    'ASL-Damage': {},
    'ASL-Dance': {},
    'ASL-Dare': { red: true },
    'ASL-Dark Blue': { red: true },
    'ASL-Dark': { red: true },
    'ASL-Date': {},
    'ASL-Day': {},
    'ASL-Dead (Variant 2)': {},
    'ASL-Dead': { red: true },
    'ASL-Deal': {},
    'ASL-Defeat (Overcome)': {},
    'ASL-Defend': { red: true },
    'ASL-Deliver': {},
    'ASL-Denial': {},
    'ASL-Dentist': {},
    'ASL-Depend': { red: true },
    'ASL-Describe': { index: true },
    'ASL-Desk': {},
    'ASL-Desktop': { red: true },
    'ASL-Diapers': {},
    'ASL-Diarrhea': {},
    'ASL-Dirty': { index: true },
    'ASL-Disagree': {},
    'ASL-Disappear': {},
    'ASL-Disappoint': { red: true },
    'ASL-Discord': { red: true },
    'ASL-Discuss': {},
    'ASL-Disguise': {},
    'ASL-Disgusted': {},
    'ASL-Dishwasher': { red: true },
    'ASL-Dismiss': {},
    'ASL-Divorce': {},
    'ASL-Doctor': {},
    'ASL-Dog': {},
    "ASL-Doll's Festival (Hina Matsuri)": { red: true },
    "ASL-Don't Know": {},
    'ASL-Donation': { red: true, index: true },
    'ASL-Door': { red: true },
    'ASL-Doubt': {},
    'ASL-Dragon': {},
    'ASL-Draw (Pencil)': { red: true },
    'ASL-DrawTie (Game)': { name: 'Draw / Tie (Game)' },
    'ASL-Dream': {},
    'ASL-Dress': {},
    'ASL-Drilling Machine': {},
    'ASL-Drink': {},
    'ASL-Drive': {},
    'ASL-Drop': {},
    'ASL-Drown': {},
    'ASL-Drum Kit': {},
    'ASL-Drunk': { red: true },
    'ASL-Dry': {},
    'ASL-Duck': {},
    'ASL-Dump': {},
    'ASL-Dust': { red: true },
    'ASL-Dwarf': {},
    'ASL-E': {},
    'ASL-Earlier': { index: true },
    'ASL-Earn': {},
    'ASL-Earring': { index: true },
    'ASL-Ears': {},
    'ASL-Earthquake': {},
    'ASL-Easter': {},
    'ASL-Eat': { red: true },
    'ASL-Ecology': { red: true },
    'ASL-Ecosystem': { red: true },
    'ASL-Edit': { red: true },
    'ASL-Effect': {},
    'ASL-Eggs': {},
    'ASL-Egypt': { red: true },
    'ASL-Elbow': {},
    'ASL-Electricity': {},
    'ASL-Elevator': {},
    'ASL-Elf': {},
    'ASL-Embarassed': {},
    'ASL-Empty': { index: true, red: true },
    'ASL-End': {},
    'ASL-Enemy': {},
    'ASL-Energy': {},
    'ASL-England': {},
    'ASL-Enjoy': {},
    'ASL-Environment': {},
    'ASL-Envy': { red: true },
    'ASL-Erase': {},
    'ASL-Eraser': {},
    'ASL-Escape': {},
    'ASL-Escort': {},
    'ASL-Europe': {},
    'ASL-Evening': {},
    'ASL-Event': { red: true, index: true },
    'ASL-Ever': { red: true },
    'ASL-Everyone': { red: true, index: true },
    'ASL-Everything': {},
    'ASL-Everytime': {},
    'ASL-Evolution': {},
    'ASL-Excited': { index: true },
    'ASL-Excuse': {},
    'ASL-Exist': {},
    'ASL-Expose': {},
    'ASL-Eye': {},
    'ASL-F': { index: true },
    'ASL-Fabric': {},
    'ASL-Fail': { index: true },
    'ASL-Faint': { red: true },
    'ASL-Fake': {},
    'ASL-Falling': { red: true },
    'ASL-Fart': { red: true },
    'ASL-Fast': {},
    'ASL-Fat': {},
    "ASL-Father's Day": {},
    'ASL-Father': { red: true },
    'ASL-Favorite': { index: true },
    'ASL-Fear': { red: true },
    'ASL-Feather': { red: true },
    'ASL-Feel': { index: true },
    'ASL-Female': {},
    'ASL-Fever': {},
    'ASL-Fiction': {},
    'ASL-Fight': {},
    'ASL-Fill': {},
    'ASL-Find': {},
    'ASL-Fine': {},
    'ASL-Finger': {},
    'ASL-Finish': {},
    'ASL-Finland': {},
    'ASL-Fire': {},
    'ASL-Fireman': { red: true },
    'ASL-Fireplace': { red: true, index: true },
    'ASL-Fireplace2': { red: true, name: 'Fireplace (Variant 2)' },
    'ASL-Firestation': { red: true },
    'ASL-First': {},
    'ASL-Fish': {},
    'ASL-Fix': {},
    'ASL-Flip': {},
    'ASL-Flirt': { index: true },
    'ASL-Flood': {},
    'ASL-Floorcarpet': { name: 'Floor / Carpet' },
    'ASL-Flower': {},
    'ASL-Fly (Insect)': { red: true },
    'ASL-Fly': {},
    'ASL-Focus': {},
    'ASL-Fog': {},
    'ASL-Foil': { red: true },
    'ASL-For': {},
    'ASL-Forbid': {},
    'ASL-Forest': {},
    'ASL-Forgive': {},
    'ASL-Fork': {},
    'ASL-Fox': {},
    'ASL-France': {},
    'ASL-Free': {},
    'ASL-Freeze': {},
    'ASL-Friday': { index: true },
    'ASL-Friendly': {},
    'ASL-Fruit': {},
    'ASL-Full': {},
    'ASL-Funny': {},
    'ASL-Future': { red: true, index: true },
    'ASL-G': {},
    'ASL-GT4tube-All Day': { name: 'All Day (Variant 2)' },
    'ASL-GT4tube-All Night': { name: 'All Night (Variant 2)' },
    'ASL-GT4tube-All1': { name: 'All' },
    'ASL-GT4tube-All2': { name: 'All (Variant 2)' },
    'ASL-GT4tube-Always': { name: 'Always' },
    'ASL-GT4tube-B-Gen': { name: 'B (Variant 2)', oculus: true },
    'ASL-GT4tube-B-Index': { name: 'B', index: true },
    'ASL-GT4tube-Busy': { name: 'Busy' },
    'ASL-GT4tube-Family': { name: 'Family', index: true },
    'ASL-GT4tube-Friends': { name: 'Friend' },
    'ASL-GT4tube-Heavy': { name: 'Heavy' },
    'ASL-GT4tube-Live': { name: 'Live (Variant 2)' },
    'ASL-GT4tube-Make': { name: 'Make' },
    'ASL-GT4tube-Month': { name: 'Month' },
    'ASL-GT4tube-Strong': { name: 'Strong' },
    'ASL-GT4tube-Teach': { name: 'Teach' },
    'ASL-GT4tube-W-Gen': { name: 'W (Variant 2)' },
    'ASL-Gain': { red: true },
    'ASL-Garbage Dump': {},
    'ASL-Garden': {},
    'ASL-Gas': {},
    'ASL-Gel': {},
    'ASL-Generator': {},
    'ASL-Geology': { red: true },
    'ASL-Germany': {},
    'ASL-Gestures': { red: true },
    'ASL-Get': {},
    'ASL-Ghost': {},
    'ASL-Girl': {},
    'ASL-Give up': {},
    'ASL-Give': {},
    'ASL-Glass': {},
    'ASL-Glasses': { red: true },
    'ASL-Gloves': { red: true },
    'ASL-Glow': { red: true },
    'ASL-Gnome': {},
    'ASL-Go Away': {},
    'ASL-Goggles': { red: true },
    'ASL-Gold': {},
    'ASL-Golden Week': { red: true },
    'ASL-Good Afternoon': { red: true },
    'ASL-Good Evening': {},
    'ASL-Good Morning': {},
    'ASL-Good Night': {},
    'ASL-Good': {},
    'ASL-Grab': {},
    'ASL-Grandma': { index: true },
    'ASL-Grandpa': {},
    'ASL-Grapes': {},
    'ASL-Grass': { red: true },
    'ASL-Graveyard': { red: true },
    'ASL-Gray': { red: true },
    'ASL-Great': { red: true },
    'ASL-Green': {},
    'ASL-Groundhog Day': { red: true },
    'ASL-Grow': { red: true },
    'ASL-Growth': { red: true },
    'ASL-Guard': {},
    'ASL-Guess': {},
    'ASL-Guide': {},
    'ASL-Guitar1': { name: 'Guitar', index: true },
    'ASL-Guitar2': { name: 'Guitar (Variant 2)' },
    'ASL-H': {},
    'ASL-Half': {},
    'ASL-Halloween': {},
    'ASL-Hamburger': {},
    'ASL-Hammer': {},
    'ASL-Happy': {},
    'ASL-Harass': { red: true, name: 'Bother / Harass' },
    'ASL-Harbor': { red: true },
    'ASL-Hard': { index: true, red: true },
    'ASL-Harm': {},
    'ASL-Hat': {},
    'ASL-Hate': { index: true },
    'ASL-Have': {},
    'ASL-Headache': {},
    'ASL-Headphone': { name: 'Headphones', red: true },
    'ASL-Headphones (Variant 2)': { red: true },
    'ASL-Headset (VR)': { red: true },
    'ASL-Healing': {},
    'ASL-Health': {},
    'ASL-Healthy': {},
    'ASL-Heaven': {},
    'ASL-Helicopter': {},
    'ASL-Hell': {},
    'ASL-Hello': {},
    'ASL-Helmet': {},
    'ASL-Her': { red: true },
    'ASL-Here': {},
    'ASL-Hidden': {},
    'ASL-Hide': { red: true },
    'ASL-High Heels': { index: true },
    'ASL-High': {},
    'ASL-Hills': {},
    'ASL-Him': {},
    'ASL-Hit': { red: true },
    'ASL-Hold': {},
    'ASL-Holiday': {},
    'ASL-Hook': {},
    'ASL-Hop': {},
    'ASL-Hope': {},
    'ASL-Hospital': {},
    'ASL-Hot Dog': {},
    'ASL-Hot': {},
    'ASL-Hotel': { red: true },
    'ASL-Hours': {},
    'ASL-House': {},
    'ASL-How Are You': {},
    'ASL-How Many': { red: true },
    'ASL-How Many2': { red: true, name: 'How Many (Variant 2)' },
    'ASL-How old are you': {},
    'ASL-How': {},
    'ASL-How_0': {},
    'ASL-Hug': {},
    'ASL-Human': {},
    'ASL-Humidity': {},
    'ASL-Hungry': {},
    'ASL-Hunt': {},
    'ASL-Hunter': {},
    'ASL-Hurricane': { red: true },
    'ASL-Hydrogen': {},
    "ASL-I can't hear you": {},
    "ASL-I don't have much time": {},
    'ASL-I have good idea': {},
    'ASL-I have to work soon': { red: true },
    'ASL-I want to change the world': { red: true },
    'ASL-I want to learn sign language': {},
    'ASL-I want to play with you': {},
    "ASL-I'm busy streaming": {},
    "ASL-I'm going to my friend's": { red: true },
    "ASL-I'm going to sleep": {},
    "ASL-I'm lost here": {},
    "ASL-I'm not feeling good": { red: true },
    "ASL-I'm slow at learning": {},
    'ASL-I': { name: 'I (person)' },
    'ASL-ILY': { index: true, name: 'ILY (I love you)' },
    'ASL-I_0': { name: 'I', index: true },
    'ASL-Ice': { red: true },
    'ASL-Icecream': {},
    'ASL-Ignore': {},
    'ASL-Imagine': { index: true },
    'ASL-Imitate': { red: true },
    'ASL-In Love': {},
    'ASL-Increase': {},
    'ASL-Independence Day': {},
    'ASL-Inside': {},
    'ASL-Instance': { red: true },
    'ASL-Insult': { red: true },
    'ASL-Interact': {},
    'ASL-Interfere': { red: true },
    'ASL-Interpreter': { index: true },
    'ASL-Invite': { red: true },
    'ASL-Ireland': {},
    'ASL-Island': {},
    'ASL-Israel': {},
    'ASL-Italy': { red: true },
    'ASL-Its': { index: true },
    'ASL-J': { index: true },
    'ASL-Jacket': {},
    'ASL-Japan': {},
    'ASL-Jeans': {},
    'ASL-Jewelry': { index: true },
    'ASL-Join': { red: true },
    'ASL-Jokes': { index: true },
    'ASL-Judge': {},
    'ASL-Juice': {},
    'ASL-Jump': {},
    'ASL-Jumpsuit': { red: true },
    'ASL-Just Kidding': {},
    'ASL-Justify': {},
    'ASL-K': { index: true },
    'ASL-Keep': {},
    'ASL-Kick': {},
    'ASL-Kill': {},
    'ASL-Kiss': {},
    'ASL-Knee': {},
    'ASL-Knife': {},
    'ASL-Knock': {},
    'ASL-Know': {},
    'ASL-L': {},
    'ASL-LOL': {},
    'ASL-Labor Day': {},
    'ASL-Lagging': { red: true },
    'ASL-Lake': {},
    'ASL-Language': {},
    'ASL-Last': { index: true },
    'ASL-Later': {},
    'ASL-Laughing': {},
    'ASL-Lava': {},
    'ASL-Lead': {},
    'ASL-Learn': {},
    'ASL-Leave': { red: true },
    'ASL-Legs': {},
    'ASL-Lemon': {},
    'ASL-Less': {},
    'ASL-Lick': {},
    'ASL-Lie': {},
    'ASL-Life': {},
    'ASL-Light Blue': { red: true },
    'ASL-Light': { red: true },
    'ASL-Lightning': {},
    'ASL-Lightweight': { index: true },
    'ASL-Like': { index: true },
    'ASL-Limited': {},
    'ASL-Lion': {},
    'ASL-Liquid': { red: true },
    'ASL-Live': {},
    'ASL-Lock': {},
    'ASL-Login': { red: true },
    'ASL-Logout': { red: true },
    'ASL-Lonely': { red: true },
    'ASL-Long': {},
    'ASL-Lose': {},
    'ASL-Low': {},
    'ASL-M': {},
    'ASL-Machine': {},
    'ASL-Magic': {},
    'ASL-Male': {},
    'ASL-Mana': { red: true },
    'ASL-Manipulate': {},
    'ASL-Many': { name: 'A Lot / Many' },
    'ASL-Marriage': {},
    'ASL-Martin Luther King Jr Day': { red: true },
    'ASL-Mask': {},
    'ASL-Matter': {},
    'ASL-Mean': {},
    'ASL-Meat': {},
    'ASL-Melee': { red: true },
    'ASL-Melt': {},
    'ASL-Memorial Day': { red: true },
    'ASL-Menu': { red: true },
    'ASL-Mess': {},
    'ASL-Metal': {},
    'ASL-Mexico': { red: true },
    'ASL-Microbes': { red: true },
    'ASL-Microphone': {},
    'ASL-Middle East': { red: true },
    'ASL-Midweek': { index: true },
    'ASL-Milk': {},
    'ASL-Milky Way': {},
    'ASL-Miniskirt': { red: true },
    'ASL-Minutes': {},
    'ASL-Miss': {},
    'ASL-Mistake': {},
    'ASL-Monday': { red: true },
    'ASL-Money': { red: true },
    'ASL-Monster': {},
    'ASL-Moon': {},
    'ASL-More': { red: true },
    'ASL-Morning': {},
    "ASL-Mother's Day": { red: true },
    'ASL-Mother': { red: true },
    'ASL-Motorcycle': {},
    'ASL-Mount': { red: true },
    'ASL-Mouse': {},
    'ASL-Mouth': {},
    'ASL-Move': {},
    'ASL-Movie': {},
    'ASL-Murder': {},
    'ASL-Must': { index: true },
    'ASL-Mute': {},
    'ASL-My friend wants to join': { red: true },
    'ASL-My name is': {},
    'ASL-My': {},
    'ASL-N': {},
    'ASL-Name': {},
    'ASL-National Day': { red: true },
    'ASL-Nature': {},
    'ASL-Necklace': { red: true },
    'ASL-Netherlands': {},
    'ASL-Never': { index: true },
    'ASL-Nevermind': { red: true },
    "ASL-New Year's Day": {},
    "ASL-New Year's Eve": {},
    'ASL-New Zealand': { red: true },
    'ASL-New': {},
    'ASL-Next Week': { red: true },
    'ASL-Next': {},
    'ASL-Nice': {},
    'ASL-Night': {},
    'ASL-No One': { red: true },
    'ASL-Nod': {},
    'ASL-Noodles': {},
    'ASL-North America': {},
    'ASL-Norway': { red: true },
    'ASL-Nose': {},
    'ASL-Not Accept': {},
    'ASL-Not': {},
    'ASL-Note': { red: true },
    'ASL-Nothing': {},
    'ASL-Notice': {},
    'ASL-Now': { index: true },
    'ASL-Number': { red: true },
    'ASL-Nurse': {},
    'ASL-Nuts': {},
    'ASL-O': {},
    'ASL-Oak': {},
    'ASL-Obey': { red: true },
    'ASL-Obsess': {},
    'ASL-Obtain': {},
    'ASL-Occupy': {},
    'ASL-Ocean': {},
    'ASL-Offend': { red: true },
    'ASL-Offer': {},
    'ASL-Offline': { red: true, index: true },
    'ASL-Often': {},
    'ASL-Oil': {},
    'ASL-Okay': { red: true, name: 'Okay / OK' },
    'ASL-Old': {},
    'ASL-Online': { red: true, index: true },
    'ASL-Open': {},
    'ASL-Or': {},
    'ASL-Orange': { red: true, name: 'Orange (color)' },
    'ASL-Orange_0': { red: true, name: 'Orange (fruit)' },
    'ASL-Orc': {},
    'ASL-Order': {},
    'ASL-Organisms': {},
    'ASL-Our': {},
    'ASL-Outer Space': {},
    'ASL-Outside (Outdoors)': {},
    'ASL-Outside': {},
    'ASL-Oven': { red: true },
    'ASL-Overalls': { index: true },
    'ASL-Overlook': {},
    'ASL-Owe': {},
    'ASL-Owl': {},
    'ASL-Own': {},
    'ASL-Oxygen': { red: true },
    'ASL-P': {},
    'ASL-Pain': {},
    'ASL-Pants': {},
    'ASL-Paper': {},
    "ASL-Parent's Day": {},
    'ASL-Parents': {},
    'ASL-Party': { index: true },
    'ASL-Pass': {},
    'ASL-Past': {},
    'ASL-Pat': {},
    'ASL-Pear': { red: true },
    'ASL-Peas': {},
    'ASL-Pencil': {},
    'ASL-Pentecost': { red: true },
    'ASL-People': { index: true },
    'ASL-Person': {},
    'ASL-Pet': {},
    'ASL-Photo': { red: true },
    'ASL-Pick': {},
    'ASL-Pig': {},
    'ASL-Pill': {},
    'ASL-Pincer': {},
    'ASL-Pine': {},
    'ASL-Pink': {},
    'ASL-Pity': { index: true },
    'ASL-Pizza': {},
    'ASL-Plastic': {},
    'ASL-Plate': { red: true },
    'ASL-Play Game': { index: true },
    'ASL-Play': { index: true },
    "ASL-Please don't disturb me": {},
    "ASL-Please don't speak": {},
    'ASL-Please follow me': {},
    'ASL-Please lead me': {},
    'ASL-Please wait for it': {},
    'ASL-Plug': {},
    'ASL-Point': {},
    'ASL-Poke': {},
    'ASL-Poland': { red: true },
    'ASL-Police Station': {},
    'ASL-Police': {},
    'ASL-Pond': {},
    'ASL-Pool': {},
    'ASL-Portal': { red: true },
    'ASL-Portugal': { red: true },
    'ASL-Potato': {},
    'ASL-Powder': {},
    'ASL-Power': { red: true },
    'ASL-Pray': {},
    'ASL-Prepare': { red: true },
    'ASL-Present': { index: true },
    "ASL-Presidents' Day": {},
    'ASL-Pretend': {},
    'ASL-Prison': {},
    'ASL-Private': { red: true },
    'ASL-Proposal': {},
    'ASL-Protect': {},
    'ASL-Prove': {},
    'ASL-Public': { red: true },
    'ASL-Publish': {},
    'ASL-Puke (Variant 2)': {},
    'ASL-Puke': {},
    'ASL-Pull': {},
    'ASL-Pumpkin': {},
    'ASL-Punch': {},
    'ASL-Punish': {},
    'ASL-Purple': {},
    'ASL-Push': {},
    'ASL-Put': {},
    'ASL-Q': {},
    'ASL-Quarter': { index: true },
    'ASL-Question': {},
    'ASL-Questions Plural form': { name: 'Questions (Plural form)' },
    'ASL-Quit': {},
    'ASL-Quote': { index: true },
    'ASL-R': {},
    'ASL-Rabbit': {},
    'ASL-Raccoon': {},
    'ASL-Race': {},
    'ASL-Radio': {},
    'ASL-Rage': {},
    'ASL-Railway': {},
    'ASL-Rain': {},
    'ASL-Rainbow': {},
    'ASL-Raincoat': { red: true, index: true },
    'ASL-Rake': {},
    'ASL-Ranged': { red: true },
    'ASL-React': { red: true },
    'ASL-Read': { red: true },
    'ASL-Receipt': {},
    'ASL-Receive': { red: true },
    'ASL-Recharge': { red: true },
    'ASL-Recommended': {},
    'ASL-Record': { red: true, index: true },
    'ASL-Recover': { red: true },
    'ASL-Red': {},
    'ASL-Refrigerator': { red: true },
    'ASL-Refuse': {},
    'ASL-Regret': { index: true },
    'ASL-Remember': {},
    'ASL-Remove': {},
    'ASL-Replace': { index: true },
    'ASL-Report': {},
    'ASL-Reproduction': {},
    'ASL-Request': { red: true },
    'ASL-Reset': {},
    'ASL-Resistance': {},
    'ASL-Restart': { red: true },
    'ASL-Resurrect': {},
    'ASL-Ride': {},
    'ASL-Ring': { index: true },
    'ASL-River': {},
    'ASL-Road': {},
    'ASL-Robot': {},
    'ASL-Rocket': {},
    'ASL-Rocks': {},
    'ASL-Romania': { red: true },
    'ASL-Roof': {},
    'ASL-Room': {},
    'ASL-Rope': {},
    'ASL-Rub': {},
    'ASL-Rubber': {},
    'ASL-Rude': { index: true },
    'ASL-Rule': { red: true },
    'ASL-Ruler': {},
    'ASL-Run': { index: true },
    'ASL-Russia': {},
    'ASL-S': {},
    'ASL-Sad': {},
    'ASL-Safe': {},
    'ASL-Salt': {},
    'ASL-Same': { index: true },
    'ASL-Sand': { red: true },
    'ASL-Sandals': {},
    'ASL-Sander': { red: true },
    'ASL-Sandwich': {},
    'ASL-Saturday': {},
    'ASL-Saudi Arabia': { red: true },
    'ASL-Save': {},
    'ASL-Saw': {},
    'ASL-Say': {},
    'ASL-Scandinavia': { red: true },
    'ASL-Scared': {},
    'ASL-Scarf': { red: true },
    'ASL-Schedule': { red: true },
    'ASL-Scissors': {},
    'ASL-Scotland': {},
    'ASL-Sea': {},
    'ASL-Search': {},
    'ASL-Season': { red: true },
    'ASL-Second': {},
    'ASL-Seconds': {},
    'ASL-Security': { red: true },
    'ASL-See': {},
    'ASL-Send': { red: true },
    'ASL-Seollal Holiday': { red: true },
    'ASL-Serve': {},
    'ASL-Sewer': { red: true },
    'ASL-Shall we begin': {},
    'ASL-Shame': {},
    'ASL-Share': {},
    'ASL-Sheep': {},
    'ASL-Shield': {},
    'ASL-Ship': {},
    'ASL-Shirt': {},
    'ASL-Shock': { red: true },
    'ASL-Shoes': {},
    'ASL-Shooting': {},
    'ASL-Shop': { red: true },
    'ASL-Short': { name: 'Short (Time)', index: true },
    'ASL-Shorts': {},
    'ASL-Shovel': {},
    'ASL-Show': {},
    'ASL-Shower': {},
    'ASL-Shut Down': { red: true },
    'ASL-Shut up': { name: 'Shut Up', red: true },
    'ASL-Shy': {},
    'ASL-Sign': {},
    'ASL-Silver': {},
    'ASL-Sing': {},
    'ASL-Single': {},
    'ASL-Sink': {},
    'ASL-Sister in Law': {},
    'ASL-Sister': {},
    'ASL-Sit': {},
    'ASL-Skeleton': {},
    'ASL-Skin': { red: true },
    'ASL-Skip': { index: true },
    'ASL-Sky': {},
    'ASL-Skyscraper': {},
    'ASL-Slow': {},
    'ASL-Small': { name: 'Small / A Little' },
    'ASL-Smart': { index: true },
    'ASL-Smell': {},
    'ASL-Smile': {},
    'ASL-Smoke': {},
    'ASL-Snow': {},
    'ASL-Socialize': { red: true },
    'ASL-Socks': {},
    'ASL-Soft': {},
    'ASL-Soil': { red: true },
    'ASL-Soldier': { red: true },
    'ASL-Someone': { red: true, index: true },
    'ASL-Sometimes': {},
    'ASL-Soon': { index: true },
    'ASL-Sorcerer': { red: true },
    "ASL-Sorry, I don't understand": {},
    'ASL-South Africa': { red: true },
    'ASL-South America': {},
    'ASL-South Korea': {},
    'ASL-Space': { index: true, red: true },
    'ASL-Spaceship': {},
    'ASL-Spaghetti': {},
    'ASL-Spain': { red: true },
    'ASL-Speak': { index: true, name: 'Speak / Talk' },
    'ASL-Spell': { name: 'Spell / Fingerspell', index: true },
    'ASL-Spine': { red: true },
    'ASL-Spit': { index: true },
    'ASL-Spoon': {},
    'ASL-Sportswear': {},
    'ASL-Spring': {},
    'ASL-Squirrel': {},
    "ASL-St Andrew's Day": {},
    "ASL-St David's Day": {},
    "ASL-St Patrick's Day": {},
    'ASL-Stairs': {},
    'ASL-Stand': {},
    'ASL-Start': {},
    'ASL-Stay': { index: true },
    'ASL-Steal': { index: true, red: true },
    'ASL-Stick': {},
    'ASL-Sticker': { red: true },
    'ASL-Stomachache': {},
    'ASL-Stop': {},
    'ASL-Storage': {},
    'ASL-Store': { red: true },
    'ASL-Storm': { red: true },
    'ASL-Stranger': {},
    'ASL-Streaming': { red: true },
    'ASL-Stressed': {},
    'ASL-Stretcher': {},
    'ASL-Structure': {},
    'ASL-Struggle': {},
    'ASL-Student': {},
    'ASL-Study': {},
    'ASL-Submarine': {},
    'ASL-Suffering': {},
    'ASL-Sugar': {},
    'ASL-Suitcase': {},
    'ASL-Summer': {},
    'ASL-Sun': { red: true },
    'ASL-Sunday': {},
    'ASL-Sunflower': { red: true },
    'ASL-Sunrise': {},
    'ASL-Sunset': {},
    'ASL-Support': {},
    'ASL-Surprise': {},
    'ASL-Sushi': {},
    'ASL-Sweater': { red: true },
    'ASL-Sweden': {},
    'ASL-Sweeper': {},
    'ASL-Swim': {},
    'ASL-Swimming Trunks': {},
    'ASL-Switch': {},
    'ASL-Sword': {},
    'ASL-T': {},
    'ASL-Table': {},
    'ASL-Taco': { red: true },
    'ASL-Take Care': { red: true },
    'ASL-Take': { name: 'Take (From)' },
    'ASL-Tan': {},
    'ASL-Tank': { red: true },
    'ASL-Tauren': {},
    'ASL-Teacher': {},
    'ASL-Teen': { red: true },
    'ASL-Television': {},
    'ASL-Tell': {},
    'ASL-Test': {},
    'ASL-Text': {},
    'ASL-Thanksgiving Day': {},
    'ASL-Their': {},
    'ASL-They': {},
    'ASL-Thin': { index: true },
    'ASL-Think': {},
    'ASL-Third': { index: true },
    'ASL-Throw': {},
    'ASL-Thursday': {},
    'ASL-Thx': {},
    'ASL-Tie': {},
    'ASL-Time': {},
    'ASL-Tired': {},
    'ASL-Today': { index: true },
    'ASL-Toilet': {},
    'ASL-Tomato': {},
    'ASL-Tomorrow': {},
    'ASL-Touch': { index: true },
    'ASL-Tower': { red: true },
    'ASL-Train': {},
    'ASL-Transparent': {},
    'ASL-Travel': {},
    'ASL-Tree': {},
    'ASL-Trip': {},
    'ASL-Troll': {},
    'ASL-Truck': {},
    'ASL-True': {},
    'ASL-Trust': { red: true },
    'ASL-Truth': {},
    'ASL-Try': {},
    'ASL-Tuesday': { red: true },
    'ASL-Turkey (Bird)': {},
    'ASL-Turkey': { name: 'Turkey (country)' },
    'ASL-Turn': {},
    'ASL-Turtle': {},
    'ASL-Type': { oculus: true },
    'ASL-U': { index: true },
    'ASL-Umbrella': {},
    'ASL-Uncle': {},
    'ASL-Undead': {},
    'ASL-Understand': {},
    'ASL-Underwear': {},
    'ASL-Uniform': {},
    'ASL-Unlimited': {},
    'ASL-Upset': {},
    'ASL-Use': {},
    'ASL-V': { index: true },
    "ASL-Valentine's Day": { red: true },
    'ASL-Value': { index: true },
    'ASL-Vegetable': {},
    'ASL-Very': {},
    'ASL-Veterans Day': {},
    'ASL-View': { red: true },
    'ASL-Village': {},
    'ASL-Visit': { red: true },
    'ASL-Vomit': {},
    'ASL-W': { index: true },
    'ASL-Wait': { index: true },
    'ASL-Wakeup': { name: 'Wake Up' },
    'ASL-Walk': { red: true },
    'ASL-Wall Outlet': { red: true },
    'ASL-Want': {},
    'ASL-War': {},
    'ASL-Warn': {},
    'ASL-Wash': { red: true },
    'ASL-Washing Machine': {},
    'ASL-Waste': {},
    'ASL-Watch': {},
    'ASL-Water Vapor': {},
    'ASL-Water': {},
    'ASL-Waterfall': {},
    'ASL-We': {},
    'ASL-Weak': {},
    'ASL-Weapon': {},
    'ASL-Wear': {},
    'ASL-Wednesday': { index: true },
    'ASL-Week': {},
    'ASL-Weekend': { red: true },
    'ASL-What are the rules': { red: true },
    'ASL-What is your Discord': {},
    'ASL-What': {},
    'ASL-What2': { name: 'What (Variant 2)' },
    'ASL-Whatsup': { index: true, name: "What's up?" },
    'ASL-Wheelchair': {},
    'ASL-When': {},
    'ASL-Where are you from': {},
    'ASL-Where': {},
    'ASL-Which': {},
    'ASL-White Day': { red: true },
    'ASL-White': {},
    'ASL-Who': {},
    'ASL-Why': {},
    'ASL-Wilderness': {},
    'ASL-Will': { name: 'Will / Future' },
    'ASL-Win': {},
    'ASL-Window': {},
    'ASL-Wine': {},
    'ASL-Winter': { index: true },
    'ASL-Wire': { red: true },
    'ASL-Wizard': { red: true },
    'ASL-Wobble': {},
    'ASL-Wonder': {},
    'ASL-Wood': {},
    'ASL-Work': {},
    'ASL-World': { red: true, index: true },
    'ASL-Worry': {},
    'ASL-Wound': {},
    'ASL-Write': {},
    'ASL-X': { index: true },
    'ASL-Y': { index: true },
    'ASL-Year': {},
    'ASL-Yellow': {},
    'ASL-Yesterday': { index: true },
    'ASL-Yogurt': {},
    'ASL-You want to become friends': { red: true },
    'ASL-Young': {},
    'ASL-Your Welcome': { name: "You're Welcome" },
    'ASL-Your': {},
    'ASL-Z': {},
    'ASL-Zombie': {},
};
