import { CategoryDefinition } from '../types/base.types';

/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable @typescript-eslint/quotes */

export const Categories: Readonly<CategoryDefinition[]> = [
    {
        name: 'Daily Use',
        words: [
            'ASL-Hello',
            'ASL-How Are You',
            'ASL-Whatsup',
            // TODO What's up (v2)
            // TODO Nice to meet you
            'ASL-Good',
            'ASL-Bad',
            // TODO Yes
            // TODO No
            // TODO So-so
            // TODO Sick - INDEX
            // TODO Sick (v2)
            // TODO Hurt
            'ASL-Your Welcome',
            // TODO Goodbye
            'ASL-Good Morning',
            'ASL-Good Afternoon',
            'ASL-Good Evening',
            'ASL-Good Night',
            // TODO See you later
            // TODO Please
            // TODO Sorry
            // TODO Forget
            // TODO Sleep / Sleepy
            // TODO Bed
            // TODO Jump / Change world - RED
            // TODO Thank you
            // TODO I love you
            'ASL-ILY',
            'ASL-Go Away',
            // TODO Going to - RED
            // TODO Follow
            'ASL-Come',
            // TODO Hearing (Person)
            // TODO Deaf
            // TODO Deaf (v2)
            // TODO Hard of Hearing
            'ASL-Mute',
            // TODO Write Slow
            // TODO Can't read
            'ASL-Away',
        ],
    },
    {
        name: 'Pointing use Question / Answer',
        words: [
            'ASL-I',
            // TODO Him/Her/He/She/It/You - RED
            'ASL-Her',
            'ASL-My',
            // TODO His/Hers/Its/Your
            'ASL-We',
            'ASL-They',
            'ASL-Their',
            // TODO Over There - RED
            'ASL-Our',
            'ASL-Its',
            'ASL-Inside',
            'ASL-Outside',
            'ASL-Outside (Outdoors)',
            'ASL-Hidden',
            'ASL-Behind',
            'ASL-Above',
            'ASL-Below',
            'ASL-Here',
            'ASL-Beside',
            // TODO Back
            // TODO Front
            'ASL-Who',
            'ASL-Where',
            'ASL-When',
            'ASL-Why',
            'ASL-Which',
            'ASL-What',
            'ASL-What2',
            'ASL-How',
            // TODO How (v2)
            'ASL-How Many',
            'ASL-How Many2',
            'ASL-Can',
            "ASL-Can't",
            'ASL-Want',
            'ASL-Have',
            'ASL-Get',
            'ASL-Will',
            'ASL-Take',
            // TODO Need - INDEX
            'ASL-Must',
            'ASL-Not',
            'ASL-Or',
            'ASL-And',
            'ASL-For',
        ],
    },
    {
        name: 'Common',
        words: [
            // TODO Teach
            'ASL-Learn',
            'ASL-Person',
            'ASL-Student',
            'ASL-Teacher',
            // TODO Friend
            'ASL-Sign',
            'ASL-Language',
            'ASL-Understand',
            'ASL-Know',
            "ASL-Don't Know",
            'ASL-Be Right Back (BRB)',
            'ASL-Accept',
            'ASL-Denial',
            'ASL-Name',
            'ASL-New',
            'ASL-Old',
            'ASL-Very',
            'ASL-Jokes',
            'ASL-Funny',
            'ASL-Play',
            'ASL-Favorite',
            'ASL-Draw (Pencil)',
            'ASL-Stop',
            'ASL-Read',
            'ASL-GT4tube-Make',
            'ASL-Write',
            'ASL-Again  Repeat',
            'ASL-Slow',
            'ASL-Fast',
            'ASL-Rude',
            'ASL-Eat',
            'ASL-Drink',
            'ASL-Watch',
            'ASL-Work',
            'ASL-Live',
            'ASL-GT4tube-Live',
            'ASL-Play Game',
            'ASL-Same',
            'ASL-Allright',
            'ASL-People',
            'ASL-Browsing the Internet',
            'ASL-Movie',
        ],
    },
    {
        name: 'People',
        words: [
            'ASL-GT4tube-Family',
            'ASL-Boy',
            'ASL-Girl',
            'ASL-Brother',
            'ASL-Sister',
            'ASL-Brother in Law',
            'ASL-Sister in Law',
            'ASL-Father',
            'ASL-Grandpa',
            'ASL-Mother',
            'ASL-Grandma',
            'ASL-Baby',
            'ASL-Child',
            'ASL-Teen',
            'ASL-Adult',
            'ASL-Aunt',
            'ASL-Uncle',
            'ASL-Stranger',
            'ASL-Acquaintance',
            'ASL-Parents',
            'ASL-Born',
            'ASL-Dead',
            // TODO!!! 'ASL-Dead (Variant 2)' ???
            'ASL-Marriage',
            'ASL-Divorce',
            'ASL-Single',
            'ASL-Young',
            'ASL-Old',
            'ASL-Age',
            'ASL-Birthday',
            'ASL-Celebrate',
            'ASL-Enemy',
            'ASL-Interpreter',
            'ASL-No One',
            'ASL-Anyone',
            'ASL-Someone',
            'ASL-Everyone',
        ],
    },
    {
        name: 'Feelings / Reactions',
        words: [
            'ASL-Like',
            'ASL-Hate',
            'ASL-Fine',
            'ASL-Tired',
            // TODO Sleep / Sleepy
            'ASL-Confused',
            'ASL-Smart',
            // TODO Attention / Focus
            'ASL-Nevermind',
            'ASL-Angry',
            'ASL-Laughing',
            'ASL-LOL',
            'ASL-Curious',
            'ASL-In Love',
            'ASL-Awesome',
            'ASL-Great',
            'ASL-Nice',
            'ASL-Cute',
            'ASL-Feel',
            'ASL-Pity',
            'ASL-Envy',
            'ASL-Hungry',
            // TODO Alive
            'ASL-Bored',
            'ASL-Cry',
            'ASL-Happy',
            'ASL-Sad',
            'ASL-Suffering',
            // TODO Surprised
            'ASL-Careful',
            'ASL-Enjoy',
            'ASL-Disgusted',
            'ASL-Embarassed',
            'ASL-Shy',
            'ASL-Lonely',
            'ASL-Stressed',
            'ASL-Scared',
            'ASL-Excited',
            'ASL-Shame',
            'ASL-Struggle',
            'ASL-Friendly',
            'ASL-Mean',
        ],
    },
    {
        name: 'Value',
        words: [
            'ASL-More',
            'ASL-Less',
            'ASL-Big',
            'ASL-Small',
            'ASL-Full',
            'ASL-Empty',
            'ASL-Half',
            'ASL-Quarter',
            'ASL-Long',
            'ASL-Short',
            'ASL-Many',
            'ASL-Unlimited',
            'ASL-Limited',
            'ASL-GT4tube-All1',
            'ASL-GT4tube-All2',
            'ASL-Nothing',
            'ASL-Ever',
            'ASL-Everything',
            'ASL-Everytime',
            'ASL-GT4tube-Always',
            'ASL-Often',
            'ASL-Sometimes',
            'ASL-GT4tube-Heavy',
            'ASL-Lightweight',
            'ASL-Hard',
            'ASL-Soft',
            'ASL-GT4tube-Strong',
            'ASL-Weak',
            'ASL-First',
            'ASL-Second',
            'ASL-Third',
            'ASL-Next',
            'ASL-Last',
            'ASL-Before',
            'ASL-After',
            'ASL-GT4tube-Busy',
            'ASL-Free',
            'ASL-High',
            'ASL-Low',
            'ASL-Fat',
            'ASL-Thin',
            'ASL-Value',
        ],
    },
    {
        name: 'Time',
        words: [
            'ASL-Time',
            'ASL-Year',
            'ASL-Season',
            'ASL-GT4tube-Month',
            'ASL-Week',
            'ASL-Day',
            'ASL-Weekend',
            'ASL-Hours',
            'ASL-Minutes',
            'ASL-Today',
            'ASL-Tomorrow',
            'ASL-Yesterday',
            // TODO???
            // TODO???
            'ASL-Evening',
            'ASL-Night',
            'ASL-Sunrise',
            'ASL-Sunset',
            'ASL-All Day',
            'ASL-GT4tube-All Day',
            'ASL-All Night',
            'ASL-GT4tube-All Night',
            'ASL-Sunday',
            'ASL-Monday',
            'ASL-Tuesday',
            'ASL-Wednesday',
            'ASL-Thursday',
            'ASL-Friday',
            'ASL-Saturday',
            'ASL-Autumn',
            'ASL-Winter',
            'ASL-Spring',
            'ASL-Summer',
            'ASL-Now',
            'ASL-Never',
            'ASL-Soon',
            'ASL-Later',
            'ASL-Past',
            'ASL-Future',
            'ASL-Earlier',
            'ASL-Midweek',
            'ASL-Next Week',
        ],
    },
    {
        name: 'VRChat',
        words: [
            'ASL-Gestures',
            'ASL-World',
            'ASL-Record',
            'ASL-Discord',
            'ASL-Streaming',
            'ASL-Headset (VR)',
            'ASL-Desktop',
            'ASL-Computer',
            'ASL-Instance',
            'ASL-Public',
            'ASL-Invite',
            'ASL-Private',
            'ASL-Add Friend',
            'ASL-Menu',
            'ASL-Recharge',
            'ASL-Visit',
            'ASL-Request',
            'ASL-Login',
            'ASL-Logout',
            'ASL-Schedule',
            'ASL-Event',
            'ASL-Online',
            'ASL-Offline',
            'ASL-Cancel',
            'ASL-Portal',
            'ASL-Camera',
            'ASL-Avatar',
            'ASL-Photo',
            'ASL-Join',
            'ASL-Leave',
            'ASL-Climbing',
            'ASL-Falling',
            'ASL-Walk',
            'ASL-Hide',
            'ASL-Block',
            'ASL-Crash',
            'ASL-Lagging',
            'ASL-Restart',
            'ASL-Send',
            'ASL-Receive',
            'ASL-Security',
            'ASL-Donation',
        ],
    },
    {
        name: 'Alphabet / Numbers (Fingerspelling)',
        words: [
            // TODO Spell / Fingerspell - INDEX
            // TODO Spell / Fingerspell (v2) - OCULUS
            'ASL-A',
            // TODO B - INDEX
            // TODO B (v2) - OCULUS
            'ASL-C',
            'ASL-D',
            'ASL-E',
            'ASL-F',
            // TODO F (v2) - OCULUS
            'ASL-G',
            'ASL-H',
            'ASL-I_0',
            // TODO I (v2) - OCULUS
            'ASL-J',
            // TODO J (v2) - OCULUS
            'ASL-K',
            // TODO K (v2)
            'ASL-L',
            'ASL-M',
            // TODO M (v2)
            'ASL-N',
            // TODO N (v2)
            'ASL-O',
            'ASL-P',
            'ASL-Q',
            'ASL-R',
            'ASL-S',
            'ASL-T',
            'ASL-U',
            // TODO U (v2) - OCULUS
            'ASL-V',
            // TODO V (v2) - OCULUS
            'ASL-W',
            // TODO W (v2)
            'ASL-X',
            // TODO X (v2)
            'ASL-Y',
            // TODO Y (v2) - OCULUS
            'ASL-Z',
            'ASL-Comma',
            'ASL-Space',
            'ASL-@',
            'ASL-Number',
            'ASL-0',
            'ASL-1',
            'ASL-2',
            'ASL-3',
            'ASL-4',
            'ASL-5',
            'ASL-6',
            'ASL-7',
            'ASL-8',
            'ASL-9',
            'ASL-10',
            'ASL-100',
            'ASL-1000',
            'ASL-1000000',
        ],
    },
    {
        name: 'Verbs & Actions (p1)',
        words: [
            'ASL-Overlook',
            'ASL-Punish',
            'ASL-Edit',
            'ASL-Erase',
            'ASL-Write',
            'ASL-Proposal',
            // TODO Add - RED
            'ASL-Increase',
            'ASL-Remove',
            'ASL-Agree',
            'ASL-Disagree',
            'ASL-Admit',
            'ASL-Allow',
            'ASL-Attack',
            'ASL-Fight',
            'ASL-Defend',
            'ASL-Defeat (Overcome)',
            'ASL-Win',
            'ASL-Lose',
            'ASL-DrawTie (Game)',
            'ASL-Give up',
            'ASL-Skip',
            'ASL-Ask',
            'ASL-Attach',
            'ASL-Assistant',
            'ASL-Assist  Help',
            'ASL-Bait',
            'ASL-Battle',
            'ASL-Beat (Overcome)',
            'ASL-Become',
            'ASL-Beg',
            'ASL-Begin',
            'ASL-Behave',
            'ASL-Believe',
            'ASL-Blame',
            'ASL-Blow',
            'ASL-Blush',
            'ASL-Harass',
        ],
    },
    {
        name: 'Verbs & Actions (p2: Ben-Cor)',
        words: [
            'ASL-Bend',
            'ASL-Bow',
            'ASL-Break',
            'ASL-Breathe',
            'ASL-Bring',
            'ASL-Construct',
            'ASL-Bully',
            'ASL-Burn',
            'ASL-Buy',
            'ASL-Call',
            'ASL-Cancel',
            // TODO???
            // TODO???
            'ASL-Catch',
            'ASL-Cause',
            'ASL-Challenge',
            'ASL-Chance',
            'ASL-Cheat',
            'ASL-Check',
            'ASL-Choose',
            'ASL-Claim',
            'ASL-Clean',
            'ASL-Clear',
            'ASL-Close',
            'ASL-Comfort',
            'ASL-Command',
            'ASL-Communicate',
            'ASL-Compare',
            'ASL-Complain',
            'ASL-Compliment',
            'ASL-Concentrate',
            'ASL-Construct',
            'ASL-Control',
            'ASL-Cook',
            'ASL-Copy',
            'ASL-Correct',
        ],
    },
    {
        name: 'Verbs & Actions (p3: Cou-Esc)',
        words: [
            'ASL-Cough',
            'ASL-Count',
            'ASL-Create',
            'ASL-Cuddle',
            'ASL-Cut',
            'ASL-Dab',
            'ASL-Dance',
            'ASL-Dare',
            'ASL-Date',
            'ASL-Deal',
            'ASL-Deliver',
            'ASL-Depend',
            // TODO???
            // TODO???
            'ASL-Disappear',
            'ASL-Disappoint',
            // TODO Disapprove
            'ASL-Discuss',
            'ASL-Disguise',
            // TODO Disgust
            'ASL-Dismiss',
            // TODO Don't Disturb
            'ASL-Doubt',
            'ASL-Dream',
            'ASL-Dress',
            'ASL-Drunk',
            'ASL-Drop',
            'ASL-Drown',
            'ASL-Dry',
            'ASL-Dump',
            'ASL-Dust',
            'ASL-Earn',
            'ASL-Effect',
            'ASL-End',
            'ASL-Escape',
            'ASL-Escort',
        ],
    },
    {
        name: 'Verbs & Actions (p4: Exc-Ins)',
        words: [],
    },
    // {
    //     name: 'Verbs & Actions (p5: Int-Pas)',
    //     words: [],
    // },
    // {
    //     name: 'Verbs & Actions (p6: Pat-Sav)',
    //     words: [],
    // },
    // {
    //     name: 'Verbs & Actions (p7: Say-Try)',
    //     words: [],
    // },
    // {
    //     name: 'Verbs & Actions (p8)',
    //     words: [],
    // },
    // {
    //     name: 'Food',
    //     words: [],
    // },
    // {
    //     name: 'Animals / Machines',
    //     words: [],
    // },
    // {
    //     name: 'Places',
    //     words: [],
    // },
    // {
    //     name: 'Stuff / Weather',
    //     words: [],
    // },
    // {
    //     name: 'Clothes / Equipment',
    //     words: [],
    // },
    // {
    //     name: 'Fantasy / Characters',
    //     words: [],
    // },
    // {
    //     name: 'Holidays / Special Days',
    //     words: [],
    // },
    // {
    //     name: 'Home stuff',
    //     words: [],
    // },
    // {
    //     name: 'Nature / Environment',
    //     words: [],
    // },
    // {
    //     name: 'Talk / Asking exercises (SEE)',
    //     words: [],
    // },
    // {
    //     name: 'Countries',
    //     words: [],
    // },
    // {
    //     name: 'Colors',
    //     words: [],
    // },
    // {
    //     name: 'Materials',
    //     words: [],
    // },
    // {
    //     name: 'Medical',
    //     words: [],
    // },
] as const;
