export type AslWord = typeof AslWords[number];

// eslint-disable-next-line @typescript-eslint/naming-convention
export const AslWords = [
    `ASL-0`,
    `ASL-1`,
    `ASL-10`,
    `ASL-100`,
    `ASL-1000`,
    `ASL-1000000`,
    `ASL-2`,
    `ASL-3`,
    `ASL-4`,
    `ASL-5`,
    `ASL-6`,
    `ASL-7`,
    `ASL-8`,
    `ASL-9`,
    `ASL-@`,
    `ASL-A`,
    `ASL-Above`,
    `ASL-Accept`,
    `ASL-Acquaintance`,
    `ASL-Add Friend`,
    `ASL-Admit`,
    `ASL-Adult`,
    `ASL-Africa`,
    `ASL-After`,
    `ASL-Afternoon`,
    `ASL-Again  Repeat`,
    `ASL-Age`,
    `ASL-Agree`,
    `ASL-Air Conditioner`,
    `ASL-Air`,
    `ASL-Aircraft`,
    `ASL-Airport`,
    `ASL-All Day`,
    `ASL-All Night`,
    `ASL-Allow`,
    `ASL-Allright`,
    `ASL-Aluminium`,
    `ASL-AmericaUSA`,
    `ASL-Ammo`,
    `ASL-And`,
    `ASL-Angry`,
    `ASL-Ankle`,
    `ASL-Anyone`,
    `ASL-Apartment`,
    `ASL-Apple`,
    `ASL-Arm`,
    `ASL-Armor`,
    `ASL-Ascension Day`,
    `ASL-Asia`,
    `ASL-Ask`,
    `ASL-Assist  Help`,
    `ASL-Assistant`,
    `ASL-At`,
    `ASL-Atmosphere`,
    `ASL-Attach`,
    `ASL-Attack`,
    `ASL-Aunt`,
    `ASL-Australia`,
    `ASL-Austria`,
    `ASL-Autumn`,
    `ASL-Avatar`,
    `ASL-Away`,
    `ASL-Awesome`,
    `ASL-Axe`,
    `ASL-Baby`,
    `ASL-Backpack`,
    `ASL-Bad`,
    `ASL-Badge`,
    `ASL-Bag`,
    `ASL-Bait`,
    `ASL-Banana`,
    `ASL-Band Aid`,
    `ASL-Bandage`,
    `ASL-Bath`,
    `ASL-Bathe`,
    `ASL-Bathroom`,
    `ASL-Battle`,
    `ASL-Be Right Back (BRB)`,
    `ASL-Beach`,
    `ASL-Bear`,
    `ASL-Beat (Overcome)`,
    `ASL-Become`,
    `ASL-Bed`,
    `ASL-Beer`,
    `ASL-Before`,
    `ASL-Beg`,
    `ASL-Begin`,
    `ASL-Behave`,
    `ASL-Behind`,
    `ASL-Believe`,
    `ASL-Belly`,
    `ASL-Below`,
    `ASL-Belt`,
    `ASL-Bench`,
    `ASL-Bend`,
    `ASL-Beside`,
    `ASL-Better`,
    `ASL-Big`,
    `ASL-Bike`,
    `ASL-Bikini`,
    `ASL-Biology`,
    `ASL-Bird`,
    `ASL-Birthday`,
    `ASL-Black Friday`,
    `ASL-Black`,
    `ASL-Blame`,
    `ASL-Block`,
    `ASL-Blond`,
    `ASL-Blood`,
    `ASL-Blow`,
    `ASL-Blue`,
    `ASL-Blush`,
    `ASL-Bone Fracture`,
    `ASL-Book`,
    `ASL-Boots`,
    `ASL-Bored`,
    `ASL-Born`,
    `ASL-Bother`,
    `ASL-Bother_0`,
    `ASL-Bow`,
    `ASL-Bowl`,
    `ASL-Box`,
    `ASL-Boy`,
    `ASL-Bra`,
    `ASL-Bracelet`,
    `ASL-Brain`,
    `ASL-Brazil`,
    `ASL-Bread`,
    `ASL-Break`,
    `ASL-Breast`,
    `ASL-Breathe`,
    `ASL-Bridge`,
    `ASL-Bring`,
    `ASL-Broom`,
    `ASL-Brother in Law`,
    `ASL-Brother`,
    `ASL-Brown`,
    `ASL-Browsing the Internet`,
    `ASL-Bulldozer`,
    `ASL-Bully`,
    `ASL-Burn`,
    `ASL-Bus`,
    `ASL-Bush`,
    `ASL-Butchery`,
    `ASL-Butter`,
    `ASL-Buy`,
    `ASL-C`,
    `ASL-Cabbage`,
    `ASL-Cake`,
    `ASL-Calculate`,
    `ASL-Call`,
    `ASL-Camera`,
    `ASL-Can we talk on Discord`,
    `ASL-Can you explain that to me`,
    `ASL-Can you help me`,
    `ASL-Can you repeat it`,
    `ASL-Can you stop that`,
    `ASL-Can you teach me`,
    `ASL-Can you write it down`,
    `ASL-Can't`,
    `ASL-Can`,
    `ASL-Canada`,
    `ASL-Cancel`,
    `ASL-Cannon`,
    `ASL-Cap`,
    `ASL-Car`,
    `ASL-Care`,
    `ASL-Careful`,
    `ASL-Carnival`,
    `ASL-Carrot`,
    `ASL-Carry`,
    `ASL-Casting`,
    `ASL-Castle`,
    `ASL-Cat`,
    `ASL-Catch`,
    `ASL-Cathedral`,
    `ASL-Cause`,
    `ASL-Cave`,
    `ASL-Celebrate`,
    `ASL-Cellar`,
    `ASL-Central America`,
    `ASL-Chain`,
    `ASL-Chair`,
    `ASL-Challenge`,
    `ASL-Champagne`,
    `ASL-Chance`,
    `ASL-Cheat`,
    `ASL-Check your Discord`,
    `ASL-Check`,
    `ASL-Cheese`,
    `ASL-Chicken`,
    `ASL-Child`,
    `ASL-Children's Day`,
    `ASL-China`,
    `ASL-Chinese New Year`,
    `ASL-Choose`,
    `ASL-Christmas`,
    `ASL-Church`,
    `ASL-City`,
    `ASL-Claim`,
    `ASL-Clay`,
    `ASL-Clean`,
    `ASL-Clear`,
    `ASL-Climate`,
    `ASL-Climbing`,
    `ASL-Close`,
    `ASL-Closet`,
    `ASL-Clouds`,
    `ASL-Coast`,
    `ASL-Cola`,
    `ASL-Color`,
    `ASL-Columbus Day`,
    `ASL-Come`,
    `ASL-Comfort`,
    `ASL-Coming of Age Day`,
    `ASL-Comma`,
    `ASL-Command`,
    `ASL-Communicate`,
    `ASL-Compare`,
    `ASL-Complain`,
    `ASL-Compliment`,
    `ASL-Computer`,
    `ASL-Concentrate`,
    `ASL-Confused`,
    `ASL-Construct`,
    `ASL-Container`,
    `ASL-Control`,
    `ASL-Cook`,
    `ASL-Cookie`,
    `ASL-Copy`,
    `ASL-Corn`,
    `ASL-Correct`,
    `ASL-Cotton`,
    `ASL-Couch`,
    `ASL-Cough`,
    `ASL-Count`,
    `ASL-Country`,
    `ASL-Cow`,
    `ASL-Crane`,
    `ASL-Crash`,
    `ASL-Create`,
    `ASL-Cricket`,
    `ASL-Crossing`,
    `ASL-Crutch`,
    `ASL-Cry`,
    `ASL-Cuddle`,
    `ASL-Culture Day`,
    `ASL-Curious`,
    `ASL-Cut`,
    `ASL-Cute`,
    `ASL-Cyber Monday`,
    `ASL-Cyborg`,
    `ASL-D`,
    `ASL-Dab`,
    `ASL-Dam`,
    `ASL-Damage`,
    `ASL-Dance`,
    `ASL-Dare`,
    `ASL-Dark Blue`,
    `ASL-Dark`,
    `ASL-Date`,
    `ASL-Day`,
    `ASL-Dead (Variant 2)`,
    `ASL-Dead`,
    `ASL-Deal`,
    `ASL-Defeat (Overcome)`,
    `ASL-Defend`,
    `ASL-Deliver`,
    `ASL-Denial`,
    `ASL-Dentist`,
    `ASL-Depend`,
    `ASL-Describe`,
    `ASL-Desk`,
    `ASL-Desktop`,
    `ASL-Diapers`,
    `ASL-Diarrhea`,
    `ASL-Dirty`,
    `ASL-Disagree`,
    `ASL-Disappear`,
    `ASL-Disappoint`,
    `ASL-Discord`,
    `ASL-Discuss`,
    `ASL-Disguise`,
    `ASL-Disgusted`,
    `ASL-Dishwasher`,
    `ASL-Dismiss`,
    `ASL-Divorce`,
    `ASL-Doctor`,
    `ASL-Dog`,
    `ASL-Doll's Festival (Hina Matsuri)`,
    `ASL-Don't Know`,
    `ASL-Donation`,
    `ASL-Door`,
    `ASL-Doubt`,
    `ASL-Dragon`,
    `ASL-Draw (Pencil)`,
    `ASL-DrawTie (Game)`,
    `ASL-Dream`,
    `ASL-Dress`,
    `ASL-Drilling Machine`,
    `ASL-Drink`,
    `ASL-Drive`,
    `ASL-Drop`,
    `ASL-Drown`,
    `ASL-Drum Kit`,
    `ASL-Drunk`,
    `ASL-Dry`,
    `ASL-Duck`,
    `ASL-Dump`,
    `ASL-Dust`,
    `ASL-Dwarf`,
    `ASL-E`,
    `ASL-Earlier`,
    `ASL-Earn`,
    `ASL-Earring`,
    `ASL-Ears`,
    `ASL-Earthquake`,
    `ASL-Easter`,
    `ASL-Eat`,
    `ASL-Ecology`,
    `ASL-Ecosystem`,
    `ASL-Edit`,
    `ASL-Effect`,
    `ASL-Eggs`,
    `ASL-Egypt`,
    `ASL-Elbow`,
    `ASL-Electricity`,
    `ASL-Elevator`,
    `ASL-Elf`,
    `ASL-Embarassed`,
    `ASL-Empty`,
    `ASL-End`,
    `ASL-Enemy`,
    `ASL-Energy`,
    `ASL-England`,
    `ASL-Enjoy`,
    `ASL-Environment`,
    `ASL-Envy`,
    `ASL-Erase`,
    `ASL-Eraser`,
    `ASL-Escape`,
    `ASL-Escort`,
    `ASL-Europe`,
    `ASL-Evening`,
    `ASL-Event`,
    `ASL-Ever`,
    `ASL-Everyone`,
    `ASL-Everything`,
    `ASL-Everytime`,
    `ASL-Evolution`,
    `ASL-Excited`,
    `ASL-Excuse`,
    `ASL-Exist`,
    `ASL-Expose`,
    `ASL-Eye`,
    `ASL-F`,
    `ASL-Fabric`,
    `ASL-Fail`,
    `ASL-Faint`,
    `ASL-Fake`,
    `ASL-Falling`,
    `ASL-Fart`,
    `ASL-Fast`,
    `ASL-Fat`,
    `ASL-Father's Day`,
    `ASL-Father`,
    `ASL-Favorite`,
    `ASL-Fear`,
    `ASL-Feather`,
    `ASL-Feel`,
    `ASL-Female`,
    `ASL-Fever`,
    `ASL-Fiction`,
    `ASL-Fight`,
    `ASL-Fill`,
    `ASL-Find`,
    `ASL-Fine`,
    `ASL-Finger`,
    `ASL-Finish`,
    `ASL-Finland`,
    `ASL-Fire`,
    `ASL-Fireman`,
    `ASL-Fireplace`,
    `ASL-Fireplace2`,
    `ASL-Firestation`,
    `ASL-First`,
    `ASL-Fish`,
    `ASL-Fix`,
    `ASL-Flip`,
    `ASL-Flirt`,
    `ASL-Flood`,
    `ASL-Floorcarpet`,
    `ASL-Flower`,
    `ASL-Fly (Insect)`,
    `ASL-Fly`,
    `ASL-Focus`,
    `ASL-Fog`,
    `ASL-Foil`,
    `ASL-For`,
    `ASL-Forbid`,
    `ASL-Forest`,
    `ASL-Forgive`,
    `ASL-Fork`,
    `ASL-Fox`,
    `ASL-France`,
    `ASL-Free`,
    `ASL-Freeze`,
    `ASL-Friday`,
    `ASL-Friendly`,
    `ASL-Fruit`,
    `ASL-Full`,
    `ASL-Funny`,
    `ASL-Future`,
    `ASL-G`,
    `ASL-GT4tube-All Day`,
    `ASL-GT4tube-All Night`,
    `ASL-GT4tube-All1`,
    `ASL-GT4tube-All2`,
    `ASL-GT4tube-Always`,
    `ASL-GT4tube-B-Gen`,
    `ASL-GT4tube-B-Index`,
    `ASL-GT4tube-Busy`,
    `ASL-GT4tube-Family`,
    `ASL-GT4tube-Friends`,
    `ASL-GT4tube-Heavy`,
    `ASL-GT4tube-Live`,
    `ASL-GT4tube-Make`,
    `ASL-GT4tube-Month`,
    `ASL-GT4tube-Strong`,
    `ASL-GT4tube-Teach`,
    `ASL-GT4tube-W-Gen`,
    `ASL-Gain`,
    `ASL-Garbage Dump`,
    `ASL-Garden`,
    `ASL-Gas`,
    `ASL-Gel`,
    `ASL-Generator`,
    `ASL-Geology`,
    `ASL-Germany`,
    `ASL-Gestures`,
    `ASL-Get`,
    `ASL-Ghost`,
    `ASL-Girl`,
    `ASL-Give up`,
    `ASL-Give`,
    `ASL-Glass`,
    `ASL-Glasses`,
    `ASL-Gloves`,
    `ASL-Glow`,
    `ASL-Gnome`,
    `ASL-Go Away`,
    `ASL-Goggles`,
    `ASL-Gold`,
    `ASL-Golden Week`,
    `ASL-Good Afternoon`,
    `ASL-Good Evening`,
    `ASL-Good Morning`,
    `ASL-Good Night`,
    `ASL-Good`,
    `ASL-Grab`,
    `ASL-Grandma`,
    `ASL-Grandpa`,
    `ASL-Grapes`,
    `ASL-Grass`,
    `ASL-Graveyard`,
    `ASL-Gray`,
    `ASL-Great`,
    `ASL-Green`,
    `ASL-Groundhog Day`,
    `ASL-Grow`,
    `ASL-Growth`,
    `ASL-Guard`,
    `ASL-Guess`,
    `ASL-Guide`,
    `ASL-Guitar1`,
    `ASL-Guitar2`,
    `ASL-H`,
    `ASL-Half`,
    `ASL-Halloween`,
    `ASL-Hamburger`,
    `ASL-Hammer`,
    `ASL-Happy`,
    `ASL-Harass`,
    `ASL-Harbor`,
    `ASL-Hard`,
    `ASL-Harm`,
    `ASL-Hat`,
    `ASL-Hate`,
    `ASL-Have`,
    `ASL-Headache`,
    `ASL-Headphone`,
    `ASL-Headphones (Variant 2)`,
    `ASL-Headset (VR)`,
    `ASL-Healing`,
    `ASL-Health`,
    `ASL-Healthy`,
    `ASL-Heaven`,
    `ASL-Helicopter`,
    `ASL-Hell`,
    `ASL-Hello`,
    `ASL-Helmet`,
    `ASL-Her`,
    `ASL-Here`,
    `ASL-Hidden`,
    `ASL-Hide`,
    `ASL-High Heels`,
    `ASL-High`,
    `ASL-Hills`,
    `ASL-Him`,
    `ASL-Hit`,
    `ASL-Hold`,
    `ASL-Holiday`,
    `ASL-Hook`,
    `ASL-Hop`,
    `ASL-Hope`,
    `ASL-Hospital`,
    `ASL-Hot Dog`,
    `ASL-Hot`,
    `ASL-Hotel`,
    `ASL-Hours`,
    `ASL-House`,
    `ASL-How Are You`,
    `ASL-How Many`,
    `ASL-How Many2`,
    `ASL-How old are you`,
    `ASL-How`,
    `ASL-How_0`,
    `ASL-Hug`,
    `ASL-Human`,
    `ASL-Humidity`,
    `ASL-Hungry`,
    `ASL-Hunt`,
    `ASL-Hunter`,
    `ASL-Hurricane`,
    `ASL-Hydrogen`,
    `ASL-I can't hear you`,
    `ASL-I don't have much time`,
    `ASL-I have good idea`,
    `ASL-I have to work soon`,
    `ASL-I want to change the world`,
    `ASL-I want to learn sign language`,
    `ASL-I want to play with you`,
    `ASL-I'm busy streaming`,
    `ASL-I'm going to my friend's`,
    `ASL-I'm going to sleep`,
    `ASL-I'm lost here`,
    `ASL-I'm not feeling good`,
    `ASL-I'm slow at learning`,
    `ASL-I`,
    `ASL-ILY`,
    `ASL-I_0`,
    `ASL-Ice`,
    `ASL-Icecream`,
    `ASL-Ignore`,
    `ASL-Imagine`,
    `ASL-Imitate`,
    `ASL-In Love`,
    `ASL-Increase`,
    `ASL-Independence Day`,
    `ASL-Inside`,
    `ASL-Instance`,
    `ASL-Insult`,
    `ASL-Interact`,
    `ASL-Interfere`,
    `ASL-Interpreter`,
    `ASL-Invite`,
    `ASL-Ireland`,
    `ASL-Island`,
    `ASL-Israel`,
    `ASL-Italy`,
    `ASL-Its`,
    `ASL-J`,
    `ASL-Jacket`,
    `ASL-Japan`,
    `ASL-Jeans`,
    `ASL-Jewelry`,
    `ASL-Join`,
    `ASL-Jokes`,
    `ASL-Judge`,
    `ASL-Juice`,
    `ASL-Jump`,
    `ASL-Jumpsuit`,
    `ASL-Just Kidding`,
    `ASL-Justify`,
    `ASL-K`,
    `ASL-Keep`,
    `ASL-Kick`,
    `ASL-Kill`,
    `ASL-Kiss`,
    `ASL-Knee`,
    `ASL-Knife`,
    `ASL-Knock`,
    `ASL-Know`,
    `ASL-L`,
    `ASL-LOL`,
    `ASL-Labor Day`,
    `ASL-Lagging`,
    `ASL-Lake`,
    `ASL-Language`,
    `ASL-Last`,
    `ASL-Later`,
    `ASL-Laughing`,
    `ASL-Lava`,
    `ASL-Lead`,
    `ASL-Learn`,
    `ASL-Leave`,
    `ASL-Legs`,
    `ASL-Lemon`,
    `ASL-Less`,
    `ASL-Lick`,
    `ASL-Lie`,
    `ASL-Life`,
    `ASL-Light Blue`,
    `ASL-Light`,
    `ASL-Lightning`,
    `ASL-Lightweight`,
    `ASL-Like`,
    `ASL-Limited`,
    `ASL-Lion`,
    `ASL-Liquid`,
    `ASL-Live`,
    `ASL-Lock`,
    `ASL-Login`,
    `ASL-Logout`,
    `ASL-Lonely`,
    `ASL-Long`,
    `ASL-Lose`,
    `ASL-Low`,
    `ASL-M`,
    `ASL-Machine`,
    `ASL-Magic`,
    `ASL-Male`,
    `ASL-Mana`,
    `ASL-Manipulate`,
    `ASL-Many`,
    `ASL-Marriage`,
    `ASL-Martin Luther King Jr Day`,
    `ASL-Mask`,
    `ASL-Matter`,
    `ASL-Mean`,
    `ASL-Meat`,
    `ASL-Melee`,
    `ASL-Melt`,
    `ASL-Memorial Day`,
    `ASL-Menu`,
    `ASL-Mess`,
    `ASL-Metal`,
    `ASL-Mexico`,
    `ASL-Microbes`,
    `ASL-Microphone`,
    `ASL-Middle East`,
    `ASL-Midweek`,
    `ASL-Milk`,
    `ASL-Milky Way`,
    `ASL-Miniskirt`,
    `ASL-Minutes`,
    `ASL-Miss`,
    `ASL-Mistake`,
    `ASL-Monday`,
    `ASL-Money`,
    `ASL-Monster`,
    `ASL-Moon`,
    `ASL-More`,
    `ASL-Morning`,
    `ASL-Mother's Day`,
    `ASL-Mother`,
    `ASL-Motorcycle`,
    `ASL-Mount`,
    `ASL-Mouse`,
    `ASL-Mouth`,
    `ASL-Move`,
    `ASL-Movie`,
    `ASL-Murder`,
    `ASL-Must`,
    `ASL-Mute`,
    `ASL-My friend wants to join`,
    `ASL-My name is`,
    `ASL-My`,
    `ASL-N`,
    `ASL-Name`,
    `ASL-National Day`,
    `ASL-Nature`,
    `ASL-Necklace`,
    `ASL-Netherlands`,
    `ASL-Never`,
    `ASL-Nevermind`,
    `ASL-New Year's Day`,
    `ASL-New Year's Eve`,
    `ASL-New Zealand`,
    `ASL-New`,
    `ASL-Next Week`,
    `ASL-Next`,
    `ASL-Nice`,
    `ASL-Night`,
    `ASL-No One`,
    `ASL-Nod`,
    `ASL-Noodles`,
    `ASL-North America`,
    `ASL-Norway`,
    `ASL-Nose`,
    `ASL-Not Accept`,
    `ASL-Not`,
    `ASL-Note`,
    `ASL-Nothing`,
    `ASL-Notice`,
    `ASL-Now`,
    `ASL-Number`,
    `ASL-Nurse`,
    `ASL-Nuts`,
    `ASL-O`,
    `ASL-Oak`,
    `ASL-Obey`,
    `ASL-Obsess`,
    `ASL-Obtain`,
    `ASL-Occupy`,
    `ASL-Ocean`,
    `ASL-Offend`,
    `ASL-Offer`,
    `ASL-Offline`,
    `ASL-Often`,
    `ASL-Oil`,
    `ASL-Okay`,
    `ASL-Old`,
    `ASL-Online`,
    `ASL-Open`,
    `ASL-Or`,
    `ASL-Orange`,
    `ASL-Orange_0`,
    `ASL-Orc`,
    `ASL-Order`,
    `ASL-Organisms`,
    `ASL-Our`,
    `ASL-Outer Space`,
    `ASL-Outside (Outdoors)`,
    `ASL-Outside`,
    `ASL-Oven`,
    `ASL-Overalls`,
    `ASL-Overlook`,
    `ASL-Owe`,
    `ASL-Owl`,
    `ASL-Own`,
    `ASL-Oxygen`,
    `ASL-P`,
    `ASL-Pain`,
    `ASL-Pants`,
    `ASL-Paper`,
    `ASL-Parent's Day`,
    `ASL-Parents`,
    `ASL-Party`,
    `ASL-Pass`,
    `ASL-Past`,
    `ASL-Pat`,
    `ASL-Pear`,
    `ASL-Peas`,
    `ASL-Pencil`,
    `ASL-Pentecost`,
    `ASL-People`,
    `ASL-Person`,
    `ASL-Pet`,
    `ASL-Photo`,
    `ASL-Pick`,
    `ASL-Pig`,
    `ASL-Pill`,
    `ASL-Pincer`,
    `ASL-Pine`,
    `ASL-Pink`,
    `ASL-Pity`,
    `ASL-Pizza`,
    `ASL-Plastic`,
    `ASL-Plate`,
    `ASL-Play Game`,
    `ASL-Play`,
    `ASL-Please don't disturb me`,
    `ASL-Please don't speak`,
    `ASL-Please follow me`,
    `ASL-Please lead me`,
    `ASL-Please wait for it`,
    `ASL-Plug`,
    `ASL-Point`,
    `ASL-Poke`,
    `ASL-Poland`,
    `ASL-Police Station`,
    `ASL-Police`,
    `ASL-Pond`,
    `ASL-Pool`,
    `ASL-Portal`,
    `ASL-Portugal`,
    `ASL-Potato`,
    `ASL-Powder`,
    `ASL-Power`,
    `ASL-Pray`,
    `ASL-Prepare`,
    `ASL-Present`,
    `ASL-Presidents' Day`,
    `ASL-Pretend`,
    `ASL-Prison`,
    `ASL-Private`,
    `ASL-Proposal`,
    `ASL-Protect`,
    `ASL-Prove`,
    `ASL-Public`,
    `ASL-Publish`,
    `ASL-Puke (Variant 2)`,
    `ASL-Puke`,
    `ASL-Pull`,
    `ASL-Pumpkin`,
    `ASL-Punch`,
    `ASL-Punish`,
    `ASL-Purple`,
    `ASL-Push`,
    `ASL-Put`,
    `ASL-Q`,
    `ASL-Quarter`,
    `ASL-Question`,
    `ASL-Questions Plural form`,
    `ASL-Quit`,
    `ASL-Quote`,
    `ASL-R`,
    `ASL-Rabbit`,
    `ASL-Raccoon`,
    `ASL-Race`,
    `ASL-Radio`,
    `ASL-Rage`,
    `ASL-Railway`,
    `ASL-Rain`,
    `ASL-Rainbow`,
    `ASL-Raincoat`,
    `ASL-Rake`,
    `ASL-Ranged`,
    `ASL-React`,
    `ASL-Read`,
    `ASL-Receipt`,
    `ASL-Receive`,
    `ASL-Recharge`,
    `ASL-Recommended`,
    `ASL-Record`,
    `ASL-Recover`,
    `ASL-Red`,
    `ASL-Refrigerator`,
    `ASL-Refuse`,
    `ASL-Regret`,
    `ASL-Remember`,
    `ASL-Remove`,
    `ASL-Replace`,
    `ASL-Report`,
    `ASL-Reproduction`,
    `ASL-Request`,
    `ASL-Reset`,
    `ASL-Resistance`,
    `ASL-Restart`,
    `ASL-Resurrect`,
    `ASL-Ride`,
    `ASL-Ring`,
    `ASL-River`,
    `ASL-Road`,
    `ASL-Robot`,
    `ASL-Rocket`,
    `ASL-Rocks`,
    `ASL-Romania`,
    `ASL-Roof`,
    `ASL-Room`,
    `ASL-Rope`,
    `ASL-Rub`,
    `ASL-Rubber`,
    `ASL-Rude`,
    `ASL-Rule`,
    `ASL-Ruler`,
    `ASL-Run`,
    `ASL-Russia`,
    `ASL-S`,
    `ASL-Sad`,
    `ASL-Safe`,
    `ASL-Salt`,
    `ASL-Same`,
    `ASL-Sand`,
    `ASL-Sandals`,
    `ASL-Sander`,
    `ASL-Sandwich`,
    `ASL-Saturday`,
    `ASL-Saudi Arabia`,
    `ASL-Save`,
    `ASL-Saw`,
    `ASL-Say`,
    `ASL-Scandinavia`,
    `ASL-Scared`,
    `ASL-Scarf`,
    `ASL-Schedule`,
    `ASL-Scissors`,
    `ASL-Scotland`,
    `ASL-Sea`,
    `ASL-Search`,
    `ASL-Season`,
    `ASL-Second`,
    `ASL-Seconds`,
    `ASL-Security`,
    `ASL-See`,
    `ASL-Send`,
    `ASL-Seollal Holiday`,
    `ASL-Serve`,
    `ASL-Sewer`,
    `ASL-Shall we begin`,
    `ASL-Shame`,
    `ASL-Share`,
    `ASL-Sheep`,
    `ASL-Shield`,
    `ASL-Ship`,
    `ASL-Shirt`,
    `ASL-Shock`,
    `ASL-Shoes`,
    `ASL-Shooting`,
    `ASL-Shop`,
    `ASL-Short`,
    `ASL-Shorts`,
    `ASL-Shovel`,
    `ASL-Show`,
    `ASL-Shower`,
    `ASL-Shut Down`,
    `ASL-Shut up`,
    `ASL-Shy`,
    `ASL-Sign`,
    `ASL-Silver`,
    `ASL-Sing`,
    `ASL-Single`,
    `ASL-Sink`,
    `ASL-Sister in Law`,
    `ASL-Sister`,
    `ASL-Sit`,
    `ASL-Skeleton`,
    `ASL-Skin`,
    `ASL-Skip`,
    `ASL-Sky`,
    `ASL-Skyscraper`,
    `ASL-Slow`,
    `ASL-Small`,
    `ASL-Smart`,
    `ASL-Smell`,
    `ASL-Smile`,
    `ASL-Smoke`,
    `ASL-Snow`,
    `ASL-Socialize`,
    `ASL-Socks`,
    `ASL-Soft`,
    `ASL-Soil`,
    `ASL-Soldier`,
    `ASL-Someone`,
    `ASL-Sometimes`,
    `ASL-Soon`,
    `ASL-Sorcerer`,
    `ASL-Sorry, I don't understand`,
    `ASL-South Africa`,
    `ASL-South America`,
    `ASL-South Korea`,
    `ASL-Space`,
    `ASL-Spaceship`,
    `ASL-Spaghetti`,
    `ASL-Spain`,
    `ASL-Speak`,
    `ASL-Spell`,
    `ASL-Spine`,
    `ASL-Spit`,
    `ASL-Spoon`,
    `ASL-Sportswear`,
    `ASL-Spring`,
    `ASL-Squirrel`,
    `ASL-St Andrew's Day`,
    `ASL-St David's Day`,
    `ASL-St Patrick's Day`,
    `ASL-Stairs`,
    `ASL-Stand`,
    `ASL-Start`,
    `ASL-Stay`,
    `ASL-Steal`,
    `ASL-Stick`,
    `ASL-Sticker`,
    `ASL-Stomachache`,
    `ASL-Stop`,
    `ASL-Storage`,
    `ASL-Store`,
    `ASL-Storm`,
    `ASL-Stranger`,
    `ASL-Streaming`,
    `ASL-Stressed`,
    `ASL-Stretcher`,
    `ASL-Structure`,
    `ASL-Struggle`,
    `ASL-Student`,
    `ASL-Study`,
    `ASL-Submarine`,
    `ASL-Suffering`,
    `ASL-Sugar`,
    `ASL-Suitcase`,
    `ASL-Summer`,
    `ASL-Sun`,
    `ASL-Sunday`,
    `ASL-Sunflower`,
    `ASL-Sunrise`,
    `ASL-Sunset`,
    `ASL-Support`,
    `ASL-Surprise`,
    `ASL-Sushi`,
    `ASL-Sweater`,
    `ASL-Sweden`,
    `ASL-Sweeper`,
    `ASL-Swim`,
    `ASL-Swimming Trunks`,
    `ASL-Switch`,
    `ASL-Sword`,
    `ASL-T`,
    `ASL-Table`,
    `ASL-Taco`,
    `ASL-Take Care`,
    `ASL-Take`,
    `ASL-Tan`,
    `ASL-Tank`,
    `ASL-Tauren`,
    `ASL-Teacher`,
    `ASL-Teen`,
    `ASL-Television`,
    `ASL-Tell`,
    `ASL-Test`,
    `ASL-Text`,
    `ASL-Thanksgiving Day`,
    `ASL-Their`,
    `ASL-They`,
    `ASL-Thin`,
    `ASL-Think`,
    `ASL-Third`,
    `ASL-Throw`,
    `ASL-Thursday`,
    `ASL-Thx`,
    `ASL-Tie`,
    `ASL-Time`,
    `ASL-Tired`,
    `ASL-Today`,
    `ASL-Toilet`,
    `ASL-Tomato`,
    `ASL-Tomorrow`,
    `ASL-Touch`,
    `ASL-Tower`,
    `ASL-Train`,
    `ASL-Transparent`,
    `ASL-Travel`,
    `ASL-Tree`,
    `ASL-Trip`,
    `ASL-Troll`,
    `ASL-Truck`,
    `ASL-True`,
    `ASL-Trust`,
    `ASL-Truth`,
    `ASL-Try`,
    `ASL-Tuesday`,
    `ASL-Turkey (Bird)`,
    `ASL-Turkey`,
    `ASL-Turn`,
    `ASL-Turtle`,
    `ASL-Type`,
    `ASL-U`,
    `ASL-Umbrella`,
    `ASL-Uncle`,
    `ASL-Undead`,
    `ASL-Understand`,
    `ASL-Underwear`,
    `ASL-Uniform`,
    `ASL-Unlimited`,
    `ASL-Upset`,
    `ASL-Use`,
    `ASL-V`,
    `ASL-Valentine's Day`,
    `ASL-Value`,
    `ASL-Vegetable`,
    `ASL-Very`,
    `ASL-Veterans Day`,
    `ASL-View`,
    `ASL-Village`,
    `ASL-Visit`,
    `ASL-Vomit`,
    `ASL-W`,
    `ASL-Wait`,
    `ASL-Wakeup`,
    `ASL-Walk`,
    `ASL-Wall Outlet`,
    `ASL-Want`,
    `ASL-War`,
    `ASL-Warn`,
    `ASL-Wash`,
    `ASL-Washing Machine`,
    `ASL-Waste`,
    `ASL-Watch`,
    `ASL-Water Vapor`,
    `ASL-Water`,
    `ASL-Waterfall`,
    `ASL-We`,
    `ASL-Weak`,
    `ASL-Weapon`,
    `ASL-Wear`,
    `ASL-Wednesday`,
    `ASL-Week`,
    `ASL-Weekend`,
    `ASL-What are the rules`,
    `ASL-What is your Discord`,
    `ASL-What`,
    `ASL-What2`,
    `ASL-Whatsup`,
    `ASL-Wheelchair`,
    `ASL-When`,
    `ASL-Where are you from`,
    `ASL-Where`,
    `ASL-Which`,
    `ASL-White Day`,
    `ASL-White`,
    `ASL-Who`,
    `ASL-Why`,
    `ASL-Wilderness`,
    `ASL-Will`,
    `ASL-Win`,
    `ASL-Window`,
    `ASL-Wine`,
    `ASL-Winter`,
    `ASL-Wire`,
    `ASL-Wizard`,
    `ASL-Wobble`,
    `ASL-Wonder`,
    `ASL-Wood`,
    `ASL-Work`,
    `ASL-World`,
    `ASL-Worry`,
    `ASL-Wound`,
    `ASL-Write`,
    `ASL-X`,
    `ASL-Y`,
    `ASL-Year`,
    `ASL-Yellow`,
    `ASL-Yesterday`,
    `ASL-Yogurt`,
    `ASL-You want to become friends`,
    `ASL-Young`,
    `ASL-Your Welcome`,
    `ASL-Your`,
    `ASL-Z`,
    `ASL-Zombie`,

    `cometxt`,
    `fortxt`,
    `goodbyetxt`,
    `gt4at2(old style)`,
    `gt4back`,
    `gt4cantread`,
    `gt4deaf`,
    `gt4deaf2`,
    `gt4follow`,
    `gt4forget`,
    `gt4front`,
    `gt4goingto`,
    `gt4googbye`,
    `gt4hearing`,
    `gt4hoh`,
    `gt4iloveyou`,
    `gt4jumpchangeworlds`,
    `gt4need`,
    `gt4nicemeetyou`,
    `gt4no`,
    `gt4overthere`,
    `gt4please`,
    `gt4seeyoulater`,
    `gt4sick`,
    `gt4sleep`,
    `gt4sorry`,
    `gt4soso`,
    `gt4take`,
    `gt4writeslow`,
    `gt4yes`,
    `hellotxt2`,
    `heretxt`,
    `hurt (fingers too far apart)`,
    `i love youtxt`,
    `nice meet youtxt`,
    `see u latertxt`,
    `sick`,
    `thankyoutxt`,
    `whats up`,
] as const;
